### ISSUE TITLE
Last Cloud Save timer incorrect on load with Auto Cloud Save disabled.

### ISSUE THREAD

**Issue by NineRed** [MelvorIdle/melvoridle.github.io#1055]
**Describe the bug**
There is a timer at the top of the Melvor page that indicates the elapsed time since the game was last saved to the cloud.
If Auto Cloud Save is disabled in settings, this timer will reset to some time prior whenever Melvor is loaded, regardless of any manual cloud saves made.
**Cloud saves themselves still work properly and no progress is lost,** this only affects the Last Cloud Save timer.

**To Reproduce**
1. Ensure you have an existing Melvor Cloud save.
2. Go to Settings -> Melvor Cloud Settings -> Auto Save to Cloud and change this to Disabled.
3. Wait a few minutes, then Force Save.  The Last Cloud Save timer should update accordingly.
4. Reload Melvor.
5. Load the latest Local or Cloud save.
6. The Last Cloud Save timer should now display a time elapsed that is greater than the time since the save made in Step 3 as expected.
This will persist with every load of Melvor until Auto Save to Cloud is re-enabled, at which point behavior goes back to normal.

**Expected behavior**
Even with Auto Cloud Save disabled, the Last Cloud Save timer should display the time elapsed since the last manual cloud save.

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/20262747/122463288-acf6aa00-cf72-11eb-86f5-b18e3b0b1022.PNG)
The timer before reloading Melvor.

![Capture2](https://user-images.githubusercontent.com/20262747/122463301-aff19a80-cf72-11eb-8863-c9af6cd4ee58.PNG)
The timer once Melvor was loaded with Auto Save to Cloud disabled.  No in-game progress has been lost.
I don't know if this would be the same for other users, but I note that the time it thinks the last save was made was at _precisely_ 7:00 PM CST, 6/16.

**Browser**
Firefox 78.11.0 on Windows 10
iOS 14.3

**Are you using any scripts?**
None

**Comment by anythingapplied** [comment]
I'm having this same issue, any chance this could be reopened? I've noticed a few things:

- It seems to always be calculating from the most recent 7 pm meaning it never reads more than 24 hours.  I haven't experimented with cloud saves that are legit more than 24 hours old since I play too frequently.
- Re-enabling autosave doesn't fix it, only makes the problem less noticeable. I also first started noticing it after I disabled autosave.  With autosave re-enabled though, the incorrect timer is still there, but only lasts a few seconds since the timer is always fixed by a in-game cloud save (both manual or automatic) and it'll always cloud save right away if autosave is enabled.  It's even possible that this was happening before I disabled autosave, I just never noticed it being wrong for a handful of seconds after the game is first loaded.


**Browser**
Chrome 95.0.4638.69 on Windows 10
Android 12

**Are you using any scripts?**
None
