### ISSUE TITLE
Firemaking - Devil Mark progression unexpectedly low burning redwoods offline

### ISSUE THREAD

**Issue by askaboutmybigrig** [MelvorIdle/melvoridle.github.io#1094]
**Describe the bug**
Devil Mark progression is unexpectedly low when burning redwoods offline, consistently earning 1-5 per 12 hours

**To Reproduce**
Equip Devil tablets and begin burning redwoods 
Wait 12 hours 
Observe mark generation 

**Expected behavior**
Using the formula on the wiki, 12 hours of skilling tier 3 mark with tablets equipped should give maybe 15-25 per 12 hours. 5 or fewer 10 times in a row is far too unlikely to be considered poor luck 

**Screenshots**
![unlucky](https://user-images.githubusercontent.com/80369069/123644749-a9c1b080-d7f3-11eb-8e86-4c5ed1d9ba06.png)

**Browser**
Chrome Version 91.0.4472.114

**Are you using any scripts?**
no

**Comment by CMudeye** [comment]
I just looked at it and I see the reason why. Offline progress with firemaking doesn't specify which log is used when rolling for marks:
`rollAllPossibleSummoningMarks(CONSTANTS.skill.Firemaking, logsData[offline.action].interval, burnInterval);
`
While online progress does specify it: 
`rollAllPossibleSummoningMarks(CONSTANTS.skill.Firemaking, logsData[selectedLog].interval, firemakingInterval, selectedLog);
`

The function will then default the log to 0 for offline progress, which corresponds to the normal log. The normal log only has a base interval of two seconds, thereby giving you a much lower chance of getting the mark than with higher end logs.
`function rollAllPossibleSummoningMarks(skill, baseInterval, interval, masteryID=0, useCharge=true) {
`

This also lowers the amount of summoning experience you get for using marks because it uses the lower interval in its calculation.
