### ISSUE TITLE
Scrollbar appearance causes infinite loop

### ISSUE THREAD

**Issue by n10262105** [MelvorIdle/melvoridle.github.io#1106]
**Describe the bug**
In runecrafting, unsure if this occurs anywhere else, but if the application is the right screensize ratio, a scrollbar appears, causing the elements to resize width and height to fit it. This new size is small enough that a scrollbar is unneeded and so it disappears, resizing the elements to the point where a scrollbar appears. This happens rapidly while on the page, and changing the size of the application or switch menus stops the issue.
Tested Mining to see if it would occur there and it did not. Character is adventure-type.

**To Reproduce**
1. Navigate to runecrafting
2. Resize desktop game to point where scrollbar is nearly gone and very slowly inrease height. Effect only occurs at specifc height and width ratios, which happened to align with my 1680x1050 monitor minus taskbar, but also when stretching diagonally on a bigger monitor to test.
3. If struggling to reproduce, increase width to the point where all gear tabs are on the same level, and resize height until scrollbar disappears, then slightly increase width.
4. Do not need to be runecrafting for effect to occur. Effect will occasionally stop for a brief period, before restarting

**Expected behavior**
When determining whether a scrollbar is visble of not, there should be a check at the start to determine whether the game window has been resized

**Screenshots**
Imaging stuttering between these two at 30-60 fps
![image](https://user-images.githubusercontent.com/62274671/124060764-0bdb1980-da71-11eb-8df0-accd315b2c3b.png)
![image](https://user-images.githubusercontent.com/62274671/124060799-1c8b8f80-da71-11eb-88e3-53f14bbe5906.png)

**Browser**
Please tell us what browser you are using and what version.
Steam Version, Windows, properites says 1.0.1.0

**Console output**
Please open the console by pressing F12 and copy it here.
Cant find console for steam version

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
No

**Comment by Laitskin** [comment]
Similar issue for me one Linux Steam Version. Hovering above the bottom-left menu makes a scrollbar show up: 
![image](https://user-images.githubusercontent.com/25294938/146687852-2b6bcb85-233f-469f-a4c0-63ba05e2eea9.png)
![image](https://user-images.githubusercontent.com/25294938/146687861-cadb714e-4de2-4d0e-a7eb-3ed9aba6dc10.png)
This also allows you to scroll horizontally infinitely:
![image](https://user-images.githubusercontent.com/25294938/146687874-cf2ffac7-d959-479a-9819-e69520766b6e.png)

I think this is caused due to the tooltip that shows up, instead of popping up to the left, it pops up to the right and causes the scrollbar to show up.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.
