### ISSUE TITLE
Crops sometimes insta-grow (still)

### ISSUE THREAD

**Issue by amicloud** [MelvorIdle/melvoridle.github.io#114]
**Describe the bug**
Seems like crops will instantly finish growing for no apparent reason. The latest patch notes say that this has been addressed but I am still seeing this bug. 

**To Reproduce**
Sorry, wish I knew. I've tried to find some correlation ever since I first noticed the bug but haven't been able to figure anything out. Best I can say is:

1. Plant crops 
2. Open up another skill or go to the bank. I'm not sure if this bug has occurred with the farming skill open or not. As far as I can recall, it always happens when I am viewing a different skill, but I can't say for sure if that is related, as I always leave the farming skill as soon as I am done planting.

**Expected behavior**
Crops take the amount of time they're supposed to to grow.

**Browser**
Chrome 80.0.3987.132

**Console output**
`MI-A04farmingAreas variable Removed Successfully
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
mastery.js?203:156 Updating Masteries
mastery.js?203:23 Loading Masteries...
smithing2.js?205:185 Loading Smithing...
main.js?237:990 Game Loaded
cloud.js?209:45 Melvor Cloud Connection: Success
save.js?225:44 Loading Save Game...
save.js?225:206 Save Game Loaded...
save.js?225:219 Save Game Deleted
mastery.js?203:156 Updating Masteries
mastery.js?203:23 Loading Masteries...
smithing2.js?205:185 Loading Smithing...
main.js?237:990 Game Loaded
cloud.js?209:158 Cloud synced
farming.js?206:595 Uncaught TypeError: Cannot read property 'mastery' of undefined
    at growCrops (farming.js?206:595)
    at farming.js?206:586
cloud.js?209:158 Cloud synced`

**Comment by amicloud** [comment]
Looks like it was just something leftover from the previous version. Have not had the error appear again. I had only noticed this happening one time after that patch, and that was very shortly after the update had gone live

**Comment by amicloud** [comment]
Actually looks like I was wrong in my last comment. I just had this bug occur again. Planted some strawberries, clicked on Smithing to look at some numbersn and the strawberries were ready for harvest within 10 seconds.

**Comment by MelvorIdle** [comment]
If there is a way to reproduce this bug 100% of the time, it will be easy to fix. The randomness makes it very hard to track down.

I have removed all leftovers from the previous version of farming, as well as added timeout clears through the code but the bug still exists.

Hopefully I can find the source soon!

**Comment by amicloud** [comment]
I'm trying to keep an eye out for anything that can help nail this down but as of right now it seems to be completely random. And any fixes I can try I have no idea if they're working of course. 

The only thing I can really think of that could be happening is that somehow plantInterval is somehow too small or the previous callback didn't actually get removed. Really neither of those cases make any sense to me, I don't see how either could happen, but yeah..

**Comment by Tom1z** [comment]
In my experience this bug occurs if you replant the crops very quickly after they finish growing. I don't know how the internal logic works, but to me it almost feels as if there is a "farming tick" every, say, minute. There are 2 farming ticks that will finish your crops and if you manage to replant the crops between them, then the second one insta-finishes them for you. Again - I say this as someone who hasn't seen the code what the bug feels like.

It doesn't matter which screen you're looking at, just replant your crops ASAP and watch as the second batch finishes for free. It's very consistent for me but I don't know if I can say it's 100% reproducable.

**Comment by Adam-Edry** [comment]
Hi, I am almost certain that this bug happens when you use the plant all button. I can't reproduce it since its hard for me to test given the time delay and gp cost.

I was not using any of the multiple crops buttons for two days and didn't encounter the bug at all and then I used the plant all button for the next set of crops and it happened right away. I confirmed this with the next set of crops too. I harvested each one separately then clicked apply weird gloop to all and then plant all and it happened within half a minute.

**Comment by DylGit** [comment]
I noticed this bug 3-4 times in the last week, Though I thought it was a bonus and not a bug. It happened when I planted a tree seed, visited the bank then switch to woodcutting and chopped down the same tree as what I just planted. I will try to reproduce it and update.

**Comment by GGallows** [comment]
I've had this bug happen 4+ times since the latest patch (0.15). I cannot recall if I had it happen prior to 0.15. This has always happened towards the very beginning of a new crops life cycle, normally within 60 seconds of planting a new crop.

THEORY: I believe this has only happened to me when a crop finishes growing, I'm actively playing the game so I'm able to quickly harvest, and plant a new crop. Soon after (within 60 seconds) another crop finishes growing, and then it looks like the game checks the rest of that type (allotments, herbs, or trees) and checks the duration of the old crop that was already harvested, and uses that outdated variable to finish the newly planted crop.
