### ISSUE TITLE
Issues with 2nd tree farming

### ISSUE THREAD

**Issue by ILLIMP** [MelvorIdle/melvoridle.github.io#1198]
When the 2nd tree chopping is activated, the game shows you reviving both items. However, you only receive 1 of the 2 items.

**To Reproduce**
1. Go to 'wood cutting'
2. Click on '2 types of trees'
3. Bottom of screen to 'receive 2 types of wood'
4. See error in inventory with 1 type of log

I am on Android using the latest version of the game. 

Thought I would give you the heads up.

**Comment by NototoHoshi** [comment]
Using multi-tree certain types of logs can become simply bugged. The woodcutting popup shows receiving the log, but when I go to bank its nowhere to be found. So those log types are basically invisible in bank.

When I go to Fletching for example, I can see the amount of logs I have, but when I go to bank, its nowhere to be found. Ive counted up the bank slots, and these invisible logs are using the bank slots as they should, but the bank UI simply doesnt show them.

It seems to be that the log types that are bugged for me are those that I harvested as secondary with the multi-tree upgrade which I previously had zero amount of bank - log types that I already had in bank before are unaffected, logs that are harvested as "primary" are also unaffected.
 
Ive tried using up all the logs so that I have zero left and then harvest some again, but they stay bugged.

Ive managed to grab this screenshot showing one of the bugged log types:

![Logs](https://user-images.githubusercontent.com/31606420/129430628-f13a1926-a0cd-4d4e-a132-57bfdae08514.jpg)

So clearly the issue seems to be that the secondary logs get assigned to nonexisting bank tab.

**Comment by coolrox95** [comment]
Issue was fixed in an update.
