### ISSUE TITLE
Smithing gloves offline

### ISSUE THREAD

**Issue by LaChoufffe** [MelvorIdle/melvoridle.github.io#1261]
**Describe the bug**
Smithing gloves does not work offline or at least the amount of charge displayed does not decrease while offline. Tested for mithril bar, mithril platebody and gold bar. Some users on reddit and discord describe the same bug.

**To Reproduce**
1. Go to 'Shop' and buy smothing gloves charges.
2. Equip Smithing gloves.
3. Go to "Smithing". Check the amount of smithing glove remaining. 
4. Scroll down to 'Mithril bar' and start production.
5. Go offline and wait 5 minutes.
6. Go online, check the amount of bar producted and the amount of charge remaining.
4. See error (no charge used)

**Expected behavior**
The number of charge remaining should decrease while performing smithing action even offline.

**Screenshots**
NA

**Browser**
Bug on Microsoft Edge, Google Chrome and on Android app.

**Console output**
NA

**Are you using any scripts?**
No sctipts used.

**Comment by fraggynator** [comment]
Did a test because I noticed the same thing.
Verified with Adamantite bars due to lack of resource preservation chance on that character.
60 ore smithed into bars, 1 glove charge used (from 1 smithing action completing before the character switch). Resulted in 4032 experience gained, suggesting that the glove bonus does get applied but the charges do not get depleted while offline.

**Comment by sherrifmarty** [comment]
Am having the same bug today, also smithing mithril bars offline on google chrome. Smithing glove charges don't get used when offline.

**Comment by coolrox95** [comment]
Issue was resolved in an update.
