### ISSUE TITLE
[Bug]: game not closing correctly (Steam)

### ISSUE THREAD

**Issue by Kkickass** [MelvorIdle/melvoridle.github.io#1712]
### Describe the bug

When Closing the game on steam it seems that it still works in the background for some reason. When I try to restart the game on steam it tells me its still running and I can only close it with my task manager it also seems to eat a lot of performance when this happens not sure if it is a steam or a melvor Problem but I never had the same issue for any other game ever 

### Screenshots

https://i.imgur.com/zcBqrGE.png https://i.imgur.com/roUOoDk.png 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1323

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you please confirm you are running the Steam client version that uses the new logo (Looks like my profile picture)

**Comment by Kkickass** [comment]
Yes I do

**Comment by Keilan** [comment]
I'm encountering the same bug (and have been since well before the current version) - I'm currently on subversion ?1329 and can confirm I also have the version using the new logo.

It seems correlated with how long I have the app open - after 15-20 minutes of running it starts to have noticeable lag after each operation finishes before the progress bar restarts. When in this state it seems to fail to close more often. However this might just be a coincidence.

**Comment by Kkickass** [comment]
I did some testing on it. It seems to happen if you have it open for a while if its only open for 5min or so it closes normally.

**Comment by EvilCrimsonWitch** [comment]
Same thing is happening to me, quite annoying.

**Comment by ssjgq** [comment]
Having same problem with 2 instances running in background. Not sure if additional info is helpful, but the Steam app still shows Melvor Idle as Running in this situation.
