### ISSUE TITLE
Clue Chasers Insignia Bug

### ISSUE THREAD

**Issue by NotArcanus** [MelvorIdle/melvoridle.github.io#175]
**Describe the bug**
Clue Chasers Insignia eliminates the chance to get gems both on and offline, and removes Chapeau and Bobby's chance offline.

**To Reproduce**
1. Equip Clue chasers insignia
2. Start Mining/Thieving
3. Close Game
4. Adjust System time 12 hours forward
5. Reopen Game

**Expected behavior**
More than absolutely 0 ever gem/bobby's/chapeau rewards

**Screenshots**
![Mining Offline](https://cdn.discordapp.com/attachments/625838709744599088/697707373082574878/unknown.png)
![Thieving Offline](https://cdn.discordapp.com/attachments/625838709744599088/697707699890028604/unknown.png)

**Notes**
This is primarily due to the code creating a random integer then multiplying it by 95% and then trying to compare to exact integers to determine drops

**Comment by NotArcanus** [comment]
I have also noticed a plethora of other smaller issues with the clue chaser insignia. Looking through the code this seems to be the full list of true effects the item has in the current game version.
    1. Breaks gem drops (if not wearing gem gloves)
    2. Doubles Chapeau and Bobby's drops online (and does variable buffs for signet depending on level)
    3. Breaks Chapeau and Bobby's drops offline
    4. Nerfs Coal from Firemaking from 39% to 35%
    5. Gets 5.26% more mastery tokens

**Comment by Tmac8622** [comment]
Thanks for posting this. I was picking through the Firemaking script and noticed that the Insignia lowers the coalChance rather than raising it, and was getting ready to check through the other skills for similar issues. 

The gemChance check requires that (gemChance === 69 || 169), so multiplying gemChance by 0.95 is not only pointless as it doesn't improve your chance to roll those two values, but it will _never_ roll those two values because there is no Math.floor() function applied to the final gemChance, meaning all the Insignia does in this case is ensure that gemChance will never end up as the whole numbers 69 or 169, hence the 0% chance. That's basically what the original poster said, just thought I'd elaborate a little bit.

In general the code handling the item not only seems to do something other than what its description might suggest, but the code handling its effects doesn't quite do what you had intended due to operator or rounding errors.

**Comment by coolrox95** [comment]
v0.16 has fixed the following bugs with cluechasers:
1. Functions correctly for bird nest drop rate with and without potions, both offline and online
2. Functions correctly for gem drop rates, both offline and online

Behavior that is still broken:
1. Still breaks the chapeau and bobby's drop chance offline, and doubles the rates online while thieving.
2. Still lowers the coal chance for firemaking, both offline and online.
