### ISSUE TITLE
[Bug]: CPU usage

### ISSUE THREAD

**Issue by JesusOnLSD** [MelvorIdle/melvoridle.github.io#1789]
### Describe the bug

CPU usage needs optimization, it's not bad but not good either and in the long run it's better to optimizate to the better.
Edit: Especially when you're visiting a page with an active progress bar.

/D

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1347

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
> Especially when you're visiting a page with an active progress bar.

This is the issue here.

We implemented new progress bar functionality with the Public Beta v1.0 update which did resolve a lot of this, however this fixed caused insane stuttering issue on iOS and Android devices. This change was reverted a few days later.

This is something we are still looking into :)

**Comment by JesusOnLSD** [comment]
Oh I see, hope you'll find a fix that suit everyone and all platforms =)

Thanks. /D

**Comment by tiatin** [comment]
@MelvorIdle Apparently high CPU usage with progress bar is because of 
```JavaScript
    setProduct(itemID, qty) {
        ...
        if (item.description !== undefined) {
            this.productDescription.append(...$.parseHTML(item.description));
        }
        ...
    }
```
inside of `artisanMenu.js`. Every time progress bar reaches its finish (in fact when timer fires) `setProduct` is called and that specific code creates a lag:
![Lags](https://user-images.githubusercontent.com/8825204/144146167-5f9a5288-37a0-44ca-8b3f-52b638621c63.png)
It is not initially noticeable, but every `setProduct()` call accumulates the lag time, and it will be unbearable already after ~100 iterations. Issue is present only if product has a description.

**Comment by MelvorIdle** [comment]
Update v1.0.4 has been released and should address this bug. Feel free to open a new issue if it persists.

**Comment by dabuside** [comment]
@MelvorIdle 
Steam version(v1.1.1 with expansion) still consumes a lot of cpu usage

OS: win11
Cpu: 3400g
Mem: 32g

In an active page consumes  ~10-30% cpu usage, no matter the windows is visible or invisible.
Non-active page consumes < 10% cpu usage
![image](https://user-images.githubusercontent.com/7280952/210233955-e01c17cb-de90-4f4a-b350-483145fa6320.png)

It works fine in web mode(chrome auto frozen unactive tabs)
1. Maybe we can achieve same [Page Lifecycle](https://developer.chrome.com/blog/page-lifecycle-api/) that frozen invisible windows to reduce cpu usage.
2. Expansion add much web content that slow the cpu down. Before I buy the expansion DLC, the cpu usage(or speed that I navigate between those pages) is acceptable. After that I see a significant delay between page visit(eg. navigate between shop page or bank page).
