### ISSUE TITLE
Back to back same slayer task

### ISSUE THREAD

**Issue by AlexFreez** [MelvorIdle/melvoridle.github.io#183]
Even tho one of the more recent changelogs said that you can no longer get back to backs of the same slayer task you can still recieve them when you skip tasks.
I just skipped a Black dragons task and got another one straight after it.

**Comment by coolrox95** [comment]
So, it looks like this occurs because the game wipes your slayer task in newSlayerTask() before calling getSlayerTask(), which causes it to not be able to know what the previous task is. Easy fix, just need need to move line 2708 of combat.js: 
`if (slayerTask.length) previousSlayerTask = slayerTask[0].monsterID;`
of getSlayerTask() before line 2787 of combat.js:
`slayerTask = []`
of newSlayerTask()

Some code snippets of the offending functions:
![image](https://user-images.githubusercontent.com/58208131/80292788-6b73c180-8716-11ea-8707-5844d33fcfbf.png)
![image](https://user-images.githubusercontent.com/58208131/80292799-80505500-8716-11ea-9762-6db61ec75a93.png)

**Comment by MelvorIdle** [comment]
Should be all good in v0.15.
