### ISSUE TITLE
[Bug]: Gold Topaz Ring Still Dropping

### ISSUE THREAD

**Issue by BakedBrotato** [MelvorIdle/melvoridle.github.io#1879]
### Describe the bug

The Gold Topaz Ring Still drops as a combat drop (versus a mummy) despite having the Gold Topaz Ring equipped as an active item. 

### Reproduction Steps

1. Equip Gold Topaz Ring
2. Combat > Browse Slayer Areas > Penumbra
3. Select Mummy
4. Recieve drops as normal. Gold Topaz Ring Still drops despite having the ring equipped. 

### Expected behaviour

Item description for gold topaz rings says that the gold topaz ring should NOT drop when the gold topaz ring is equipped. "Something else" should drop instead. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?1356

### Are you using any scripts or extensions?

No

**Comment by simonkrol** [comment]
That is expected behaviour, the "should NOT drop, something else instead" is referring to the signet ring half, which is a rare drop that would normally be replaced by a gold topaz ring unless you have one equipped. For regular gold topaz ring drops, you'll always get the gold topaz ring. You can read more about the signet ring and it's halves at (https://wiki.melvoridle.com/w/Aorpheat%27s_Signet_Ring). I agree that the wording might be worth changing (but I can't think of any way to make it better), however, the functionality is working as expected.

**Comment by BakedBrotato** [comment]
Thank you for the clarification. If I may make a suggestion:  Perhaps striking the "gold topaz ring will not drop" part would be beneficial. Instead, call the attention to the signet half by mentioning that you must have the gold topaz ring equipped as a pre-requisite for the signet half drop. Keep the wording about "something else" dropping. Just get rid of the part where it says the gold topaz ring won't drop. Current wording implies no topaz ring duplicates as regular drops.
