### ISSUE TITLE
Combination Runes not behaving as expected[Bug]: <title>

### ISSUE THREAD

**Issue by Runemaster88** [MelvorIdle/melvoridle.github.io#1880]
### Describe the bug

I was trying to use steam & mud runes  (I also just noticed I had an earth battle staff equiped) instead of fire runes and lava runes for casting Superheat 3. It wouldn't allow me to do that despite having all the other requirements for the spell.  Is there a way we can get the spells to allow us to select which runes we want to use, even if we select an inefficient option? 

### Reproduction Steps

1) Obtain mud and steam runes
2) Obtain ore to make into bars
3) Ensure you have 3 or less Lava runes
4) Go into Alt Magic
5) Select Superheat 3 
6) check use combination runes
7) click cast

### Expected behaviour

A) use steam  & mud runes and would have proceeded to cast the spell. 
B) Recognized I had an earth battle staff equiped and use the steam rune and proceed to cast the spell.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

?361

### Are you using any scripts or extensions?

No

**Comment by imperialboy3** [comment]
You can only use a combination rune that covers both of the elemental runes required by a spell. In the code each spell has a list of required runes and an alternate list with just one applicable combination rune. It is understandable that you'd want it to work that way, as it does on Runescape, but I would not consider it a bug/glitch.

**Comment by Runemaster88** [comment]
I wouldn't expect that it would have use both elements or nothing for them which is how you are saying it is coded.  

Yes, I could opt to just not use combination runes and be faster that way as I could create a massive stockpile of indivudal elements, but then in essence that is just forcing us to create combination runes for those who chase after skill masteries and never create them again after the fact. The only thing I see is that makes combination runes a lot weaker; yes they are good for skill exp and that is it but it is just something you'd have to specifically plan for rather "oh hey can use smoke and mud to cover all my elemental needs". 

Realistically there are 6 combination runes, 4 elemental runes. As expensive as bank slots get, it seems like 4 elemental runes are more space efficient if you are hoarding them to do a variety of spells that use different elements.

**Comment by imperialboy3** [comment]
In theory, "fire rune" could be treated as a category rather than a specific item then steam, lava, and smoke runes would all have that category. Then the problem of how to choose which runes to use is actually pretty complicated:

Superheat3 uses 4 earth+4 fire
Scenario 1: You have 1 smoke rune, 1 steam rune, 1 lava rune, 1 fire rune, 1 dust rune, 1 mud rune, and 1 earth rune. 
Q. Should you be able to cast it?
Q. Will you have to select all 7 of those manually or will the game figure it out for you?
Q. If you had a million of each how would it decide which to use if you selected them all?
Scenario 2: You have lava runes and earth runes.
Q. Should you be able to select both even though the lavas are sufficient alone?
Q. If not, what if you selected the earth runes first?

Possible solution: Limit the user to select 2 elemental/combination runes. Default the user to the "correct" combination rune.  If the user selects a wasteful combination just let it happen. Let the user select the rune that their equipped staff covers but don't actually use them.

**Comment by Runemaster88** [comment]
1) I think this seems tedious but if it was to be done exactly like rs, yes but I wasn't hoping for that much.
2) I'd be okay with us having to manually select the runes with defaulting on what would be more efficient.
3) I'd think a manual selection would be simper when we can just have "X element comes from Y Combo rune" this does however make Q1 a no.
4) I think the easiest thing would be yes; but if it is done 'right' no.
5) It would unselect the earth runes and move the lava runes to be the first selection.

What I see is we could have an option for each spell or each elemental source -- it would be easier to do it for each elemental source as then players would lean to either just not use combo runes or wouldn't care about inneficiencies but they would still be a valid option for saving bank space even if it wastes time for only using 1 of the elements at once.

**Comment by MelvorIdle** [comment]
Closing this due it not being a bug (And can also confirm combination runes are on our list to look at further)
