### ISSUE TITLE
[Bug]: App Zoomed in on Samsung devices with Android Webview v99

### ISSUE THREAD

**Issue by godoffrock41** [MelvorIdle/melvoridle.github.io#2290]
### Describe the bug

When opening the app on a Samsung Note 10+ it is extremely zoomed in. Restarting my phone fixed it once but it happened again and now that won't fix it. Force stopping the app and reopening it doesn't fix it either.

### Screenshots

![Screenshot_20220303-234100_Melvor Idle](https://user-images.githubusercontent.com/100957100/156804884-b4ee3e2a-821f-4bd1-8359-02433a3108f7.jpg)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1822

### Are you using any scripts or extensions?

No

**Comment by JohnnyJBravo** [comment]
I'm having the exact same issue. Also on S10+, restarting phone did not fix for me

**Comment by MuppyTheMuppy** [comment]
Same problem on Samsung S20 FE. It seems to affect only Samsung phones from screenshots I have seen

**Comment by DevoutSkeptic29** [comment]
Having the same issue on Samsung Galaxy S20 FE 5G. Restarting did not fix the issue. Screenshots below. Almost unplayable.
![Screenshot_20220305-120752_Melvor Idle](https://user-images.githubusercontent.com/74685808/156898537-aad14e3f-cf7c-4d7d-88d6-73f61bc1234f.jpg)
![Screenshot_20220305-120817_Melvor Idle](https://user-images.githubusercontent.com/74685808/156898543-b57766f7-093f-4af8-9e03-7bdcb3a944e7.jpg)

**Comment by Koristica** [comment]
Same bug on a Samsung S22 Ultra. Seems to be localized to Samsung devices,

**Comment by Jond8796** [comment]
Also having the same issue, only restarting phone shortly fixes the issue.

**Comment by DevoutSkeptic29** [comment]
Here's a summary of what I've noticed after testing on my Galaxy S20 FE 5G:
- Restarting phone then opening Melvor fixes the issue
- If the game is closed, reopening it will cause the scaling to zoom in way too far
- Restarting the phone again fixes the issue, but it reappears if the app is close and reopened
- Might be unrelated, but the game itself seems to be glitching since the last update. 
Example: I'm in combat, but the Woodcutting name is highlighted green in the side menu as if I'm actively using that skill. 
- Also general lagging when switching menus or doing anything really. The lag is worse when the zoom issue is present. 
- No issues at all on browser version.

**Comment by theRealUtopiaMan** [comment]
Having the same issue on SEQ Ultra

**Comment by coolrox95** [comment]
This issue occurs when using a Samsung device with Android 12, OneUI v4.0 and Android System Webview v99. 

This appears to be impacting other applications and a report has been filed regarding this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1305201

As a temporary workaround while this issue is being resolved, uninstalling updates to Android System Webview may work.

**Comment by DevoutSkeptic29** [comment]
> This issue occurs when using a Samsung device with Android 12, OneUI v4.0 and Android System Webview v99.
> 
> This appears to be impacting other applications and a report has been filed regarding this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1305201
> 
> As a temporary workaround while this issue is being resolved, uninstalling updates to Android System Webview may work.

Can confirm that uninstalling the updates to Android System Webview completely fixed all the issues on S20 FE, including the lagging. Thank you!

**Comment by JohnnyJBravo** [comment]
BE CAREFUL WHEN DOING THIS!!!!! Make sure you have backed up all your local saves to the cloud. Uninstalling the system webview updates WILL delete your local files. 

Just lost over a week's worth of work. Thanks for the warning.....

**Comment by DevoutSkeptic29** [comment]
> 

Sorry mate! I had already deleted my local saves trying other fixes so didn't realize that happened.

**Comment by JohnnyJBravo** [comment]
You're alright, I'm over it. Had some post nut clarity and realized i dont care

**Comment by larshb** [comment]
Is this fixable or do Samsung-users have to not update WebView?

**Comment by charlesabarnes** [comment]
After not playing for a while I found another workaround to try that worked on my device.  

In the galaxy store I installed the app "game plugins" in that app i went to game booster plus, selected melvor, then custom, and turned all settings to 100%.  

This fixed my issues. I got this solution from the chromium comments.
