### ISSUE TITLE
[Bug]: Welcome Back Screen Repeats Multiple Times upon Coming Back

### ISSUE THREAD

**Issue by ssjgq** [MelvorIdle/melvoridle.github.io#2321]
### Describe the bug

v1.0.3 game running in Chrome 99.0.4844.51 on Windows 11

When leaving the game open in a background window, I'm presented with multiple Welcome Back screens. This happens no matter what I do in the foreground. 

I've attached a gif showing the behavior. I usually get 5-10 Welcome Backs, but have seen it well over 15-20 at times.

### Reproduction Steps

1. Leave game running in background in Chrome
2. Do various other things and don't check on game
3. Come back and multiple Welcome Back screens appear

### Expected behaviour

Only 1 Welcome Back screen should appear as I only go back to game once.

### Save Link

https://melvoridle.com/save/XVA3hiwW

### Screenshots

![SoManyWelcomeBacks](https://user-images.githubusercontent.com/59457500/157994791-de525e95-d704-47bf-9d75-ad53a51325ae.gif)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1848

### Are you using any scripts or extensions?

Yes

**Comment by ssjgq** [comment]
After playing with this some more it's clearly something to do with the taskbar preview of Windows. I can reproduce this by:
1. Putting game window fully behind another window (must be maximized)
2. Hovering over open windows in the taskbar. 
3. Everytime I hover and get a window preview from the taskbar, I also invoke another Welcome Back dialog box

**Comment by yuriks** [comment]
I have a similar issue. Leaving a browser window with Melvor as the foreground tab causes this issue to happen to varying degrees. I use Windows **10** and Firefox 98. I think it's gotten much more common and severe for me with a recent Firefox update, but it always happened occasionally.

One workaround is to make sure to switch to a different tab in that browser window, however I think the game should really be coalescing periods of offline instead of relying on the browser to send only the minimal number of events. (There's a related bug where the browser occasionally will happen to not send backgrounding events *at all*, and upon switching back to the tab the screen is simply flooded with mini popup notifications for all the actions that happened while in the background at the same time.)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
