### ISSUE TITLE
Android client lag

### ISSUE THREAD

**Issue by ACrenshaw** [MelvorIdle/melvoridle.github.io#2355]
### Describe the bug

Over the past several weeks Ive been experiencing a lot of lag on the android client, I've tried reinstalling the app several times and clearing the cashe with no avail. 
Google pixel 4a
Android version 12

### Reproduction Steps

Any activity in game

### Expected behaviour

Lag and loss of frame rate

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

1582

### Are you using any scripts or extensions?

No

**Comment by tomgravell** [comment]
I reported this on Reddit a few weeks back where a handful of other people reported they were seeing the same issue in similar circumstances.

It seemed to happen almost immediately after an update, I think it was around the time the 'offline progress' bug was fixed?

Describe the bug
Lag making the game unplayable on mobile device.
OnePlus 9 Pro
Android 11 and continues after recent upgrade to 12

Reproduction Steps
Open the game. select a save and immediately after loading the game is running very slowly.

Expected behaviour
Continuous lag, even after the inital 'offline progress' screen has been passed

Save Link
No response

Screenshots
No response

Console output
No response

Which platforms are you experiencing this bug on?
 Chrome
 Firefox
 Edge
 Safari
 Mobile App (iOS)
 **Mobile App (Android)**
 Steam
 Other (Please Specify)

Which version of the game are you experiencing this bug on?
2.02 (current playstore version)

Game Subversion
Unsure where to find this information

Are you using any scripts or extensions?
No

**Comment by Deanosim** [comment]
I'm also having this problem on OnePlus 5 running Android 12, makes the game very difficult to play.

**Comment by kyle-okeeffe** [comment]
I have been seeing this issue as well. I have a Pixel 5. I see multiple similar reviews on the Play Store when filtering reviews by device.

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
