### ISSUE TITLE
[Bug]: Global Mastery XP Bonus Not Being Applied in Hardcore Adventure Speedrun

### ISSUE THREAD

**Issue by TyH621** [MelvorIdle/melvoridle.github.io#2380]
### Describe the bug

Bonus Mastery XP Not Applied To Thieving in Hardcore Adventure Speed Run

### Reproduction Steps

1. Start a Hardcore Adventure Speed Run
2. Unlock Thieving Skill
3. 800% Mastery XP Bonus not applied to any thieving npcs

### Expected behaviour

The 800% Mastery XP Bonus is not being applied to the Thieving Skill. Thieving NPCs should have 800% increased Mastery XP and Mastery Pool XP.

### Save Link

https://melvoridle.com/save/z42LVJAC

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [x] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

No

**Comment by TyH621** [comment]
This seems to be the case on most skills. The mastery bonus exists on cooking, but does not exist on mining. I will continue to update with affected skills if needed.

**Comment by mattbaron0** [comment]
I believe this is working correctly based on what's documented of the mastery calculation.

https://wiki.melvoridle.com/w/Mastery

The mastery calculation has "action time" as part of the mastery/action calculation. For most skills (specifically gathering skills -- thieving, mining, etc) the action time used in the calculation is the actual time per action. So if you decreasing your thieving interval, you decrease the mastery XP you earn per action, but keep earning the same total mastery XP per hour. If you compare the mastery XP/action on gathering skills on a new hardcore adventure speedrun character to a normal character, you'll see that the mastery XP/action is higher on the speedrun character, despite action time being much shorter -- and if you do the math on the difference, I believe the 800% bonus IS working.

What really throws things off with speedrun is that production skills have a FIXED action time (as documented on wiki). So as an example, fletching uses 1.7 as action time in the mastery XP/action calculation, even though you can have an action time of 0.25 in speedrun. This results in production skills having MUCH higher XP/action in speedrun, since they aren't impacted by the decreased action time in speedrun mode.

This is weird and a little unbalanced, but this is an April Fools event, so it is what it is.

Hope this helps!
