### ISSUE TITLE
[Bug]: Extra undefined masteries in farming.

### ISSUE THREAD

**Issue by SavvySquid** [MelvorIdle/melvoridle.github.io#2445]
### Describe the bug

I'll be honest, I did some save recovery cheating about 2 months ago or so. I'm not sure if these extra masteries popped up as a result of what I did, and I don't exactly remember what I did to get them, but they are there, and weren't in the save that I lost. I ignored them as they weren't really doing anything, but after getting to "100% mastery" and level 120 farming, I noticed that they actually impact my farming mastery progress. 

(side note, I took the opportunity of getting the console to also get ETA and Combat Simulator as well (two other mods). I doubt they are causing the problem, but it's worth it to note at least)

### Reproduction Steps

1. Stupidly lose your save
2. Start a new one and cheat everything back
3. ???

### Expected behaviour

Not having extra masteries I suppose.

### Save Link

https://melvoridle.com/save/dhrkZG9Z

### Screenshots

![Extra Masteries](https://user-images.githubusercontent.com/102441028/168683902-69ff13cf-532e-4760-b8b5-b63e6c27d8dd.JPG)

(there are quite a few of them)

![Extra Masteries 2](https://user-images.githubusercontent.com/102441028/168683906-ed8c4df9-798a-47ea-b486-0794f2a4ac58.JPG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1877

### Are you using any scripts or extensions?

Yes

**Comment by Silberdrachi** [comment]
When using the commands from the wiki, please make sure you follow the format closely this is a common mistake that is generally because the user forgot to add a parameter in the middle of the command to define which mastery it was adding xp to.  To resolve this you can use a command like this `MASTERY[Skills.Farming].xp.splice(24)` where the number in the splice is the INTENDED number of mastery items in a skill.
Fixed Save Link:
https://melvoridle.com/save/zuol9YFq
