### ISSUE TITLE
Guardian Amulet reducing DR in dungeons

### ISSUE THREAD

**Issue by blahberguy** [MelvorIdle/melvoridle.github.io#256]
**Describe the bug**
DR from Guardian Amulet gets reset halfway while fighting a monster and resets to -12 after defeating the monster in the dungeon

**To Reproduce**
1. Go to Air Dungeon (may occur in other dungeons)
2. Reach Floor 3 (Air Golem)
3. Alt+Tab to another window (might not affect)

**Expected behavior**
DR is supposed to reset to base DR after defeating monsters

**Screenshots**
After it resets from 54 DR to 42
![melvor_guardianbug](https://user-images.githubusercontent.com/66079103/83166828-0ca0ce00-a142-11ea-9bca-42f769941b0b.jpg)
After defeating Air Golem reduces DR by 12
![melvor_guardianbug2](https://user-images.githubusercontent.com/66079103/83166836-0f9bbe80-a142-11ea-90c2-a3071710df24.jpg)

**Browser**
Chrome Version 83.0.4103.61

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
No

**Comment by Cadbury847** [comment]
Encountered the same issue.
Seems to be due to the buff expiring after however much time which will reduce your DR back to base, then when the fight ends it reduces it again - but the reduction when the fight ends reduces your DR by (current buff + previous buffs), when it should just be current buff.

Easy example of it since my explanations suck:
Amulet grants you +6% damage reduction. This expires, and removes the 6% buff.
In the same fight, the amulet grants you another 10% DR buff. Then the kill ends, removing a total of 16% from your DR instead of just the current 10%.  So it's just one variable causing the issue by not being reset? 

Hope that makes it easier to track down

**Comment by MelvorIdle** [comment]
Fixed in an upcoming update
