### ISSUE TITLE
Mastery Tokens

### ISSUE THREAD

**Issue by masterryanof** [MelvorIdle/melvoridle.github.io#275]
**Describe the bug**
If you use multiple mastery tokens at once, for instance spam clicking a bulk stack, and it uses the token on the same thing twice, it doesn't go up two.

My Situation as an example: 
I was 70 mastery on Mithril Javelin Heads
I had 141 Smithing Mastery Tokens
I spam clicked all of them
I noticed that I saw it say 71 next to it 3 or 4 times
I assumed it'd just say 74 or 75 when I went and checked.
Still 71.

**To Reproduce**
1. Go to inventory
2. Click on bulk mastery tokens
3. Spam Click "Use" and hope to get the same object twice
4. You'll see it won't increase again on the second one.

**Expected behavior**
The other mastery tokens to increase my mastery level on the item.

**Browser**
Google Chrome

**Are you using any scripts?**
No

**Comment by masterryanof** [comment]
It works for Runecrafting
It does not work for Smithing

**Comment by dgnt** [comment]
This seems tied to Smithing, not spamming.

I've noticed the same thing when I collect a smithing token and see the corresponding skill up, the mastery achieved is the same tier the skill was already on.  After looking at the skill there is no additional progress visible on the mastery progress bar.  After smithing the item there is still no change in mastery.  As far as I can tell the mastery token did not work.

Not 100% reproducible as I do see it work *sometimes*, and it's not item dependent either since I've seen it both work and not work for the same item type.  Unclear to me what causes it.  I've only encountered this with smithing tokens.  Previously I'd noticed similar with other tokens where it doesn't seem to have given a level up, but when you craft the item once it updates (purely visual issue).  With smithing this does not seem to be the case.

I'm also on the Chrome browser.

**Comment by MeaKyori** [comment]
Noting that I'm having the same issue on the app as well. Have had multiple items have their mastery go "up" to 1, sometimes multiple times in a row.

**Comment by ChrisWord** [comment]
Smithing looks to have some unique ID handling within the levelUpMastery function (in mastery.js) that isn't taken into consideration when calling levelUpMastery in the claimToken function (in bank.js). The result is that the mastery level up toast from consuming smithing mastery tokens shows the wrong item. For example a token that would effect Dragon Javelin Heads produces the pop up for Dragon Helmet.
