### ISSUE TITLE
Township: Potion tasks only accept tier 1 potions

### ISSUE THREAD

**Issue by dsk555** [MelvorIdle/melvoridle.github.io#2801]
### Describe the bug

I cannot complete my easy herblore task in township as the task requires tier 1 potions (bird nest, controlled heat, generous cook) and my mastery level is higher which only allows me to produce higher tier potions.

### Reproduction Steps

Have mastery 20+ of Bird nest, Controlled heat, or Generous cook potions
Craft
Receive X potion II or higher
Cannot be used for the easy township task requiring 25 of each

### Expected behaviour

Allow higher tier potions to substitute 
Or allow crafting of lower mastery potions

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4598

### Are you using any mods?

No

**Comment by FanFaniel** [comment]
You can use Herblore Potion, which gives you chance to obtain random tier of the same potion during crafting.

**Comment by IRONN1C** [comment]
Fanfaniel is right, this take obviously more time but that's how I did it too !

**Comment by earchibald-lv** [comment]
This is still, in relation to how the rest of the game behaves, a bug. Players should not be penalized for progressing in the "wrong" order, particularly without being warned.

**Comment by earchibald** [comment]
While it's possible to complete this task, according to the way the rest of the game plays, this is a bug. Certainly, the lack of messaging itself is a bug, even if this design intent remains in place. It is simply not credible to the average player that things would work this way.

Players should not be penalized for doing tasks in the "wrong" order, particularly when they have not been warned. This is buried deep within Township; a **lot** of players are going to run into this and be confused/annoyed.

**Comment by Pinchanzee** [comment]
Pretty outstanding that the final decision on this was "not a bug".  It's just unquestionable terrible user experience, how could this possibly have been considered a good workaround to the problem?

As a person just starting out on this game (rather than someone who had high herblore before township came out), it's pretty annoying that I've been working towards level 32 in herblore specifically to do this task, only to discover I now need to work to level 72.  I imagine it's easy to get desensitized to it but level 72 isn't a small deal early/mid game for a quite uninteresting skill.
