### ISSUE TITLE
[Bug]: Apple Pies not adding to bank after successful cook

### ISSUE THREAD

**Issue by LlamaJerky** [MelvorIdle/melvoridle.github.io#2820]
### Describe the bug

Apple pies are not adding to my bank after being successfully cooked, it just pops up “+1 (0)” after every cook. Strangely this isn’t an issue with the perfect apple pies, just the basic ones. I am unaware if this is a server-wide issue.

### Reproduction Steps

1. Go to cooking tab. 2. Select apple pies as recipe in furnace. 3. Select “active cook” button. 4. Wait for a successful cook. 5. The “+1 (0)” message will pop up for every successful cook and there will be no apple pies in your bank

### Expected behaviour

I expected the apple pie to appear in my bank when successfully cooked, giving me a “+1 (n)” message, n being the number of apple pies I have previously successfully cooked.

### Save Link

https://melvoridle.com/save/tnrMsFZI

### Screenshots

![59A13028-CC22-4EC7-92B6-74BB4383BAF9](https://user-images.githubusercontent.com/116763832/198135839-79ed6404-6be2-44a6-95d0-d9b120ffbb70.jpeg)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4628

### Are you using any mods?

Yes

**Comment by AlexWinder** [comment]
Same issue for me with whale. Affects both normal and perfect cooks.

**Comment by Kopokan** [comment]
Same issue for me (Or very similar)
I'm trying to cook Carp for the township task
- It is consuming raw carp
- I am getting EXP
- I am not getting any normal carps
- I AM getting my perfect cooks
- I tried switching between my android app and Steam (Ver. ?4695 for both) and issue persists
- Other skills work fine though I haven't tried literally all of them (Like Astrology, fishing, and smithing)|
- I tried cooking something else (bread) and it worked just fine.
- After completing my task and selling off all cooked carp the issue persists
- After selling off my raw carp and fishing up more the issue persists. 

- Not sure if relevant but I had to force kill the game in order to close it on my PC. I've never had to do this before

I think that's everything I observed about this, I hope this information is helpful. I'd upload my save but I admit I don't know where to find it or how to exactly do that.

**Comment by AlexWinder** [comment]
I have since found out that a possible solution to this is that food is equipped in the combat tab. When it is successfully cooked it is being added to the food which is equipped.

**Comment by coolrox95** [comment]
As per the commenters, your food was being automatically equipped.
