### ISSUE TITLE
[Bug]: lost all meteorite i had built up from astrology 

### ISSUE THREAD

**Issue by Bwild327** [MelvorIdle/melvoridle.github.io#2902]
### Describe the bug

Went to start mining the 120k meteorite I had built up and it was all gone and the game had started to recollect it all over again from base 0.

### Expected behaviour

Please resolve this. Spent over a week building it up just to have it vanish.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This issue was due to the expansion data failing to load, but still allowing you to load in a save resulting in lost save data. Unfortunately we are unable to recover this data. This was fixed with v1.1.1 (?5023). It should no longer be possible to load a save if expansion data fails to load due to networking (or other) errors.
