### ISSUE TITLE
Combat issue and TypeError: bank[i] is null

### ISSUE THREAD

**Issue by insanesquirle** [MelvorIdle/melvoridle.github.io#292]
I was afk training combat on wizards, it was working fine, came back later and the wizard was stuck at 0 HP.  I was unable to hit or kill it.  I figured it was a fluke so I saved my game and refreshed the page.  Upon refreshing I got the following error:
TypeError: bank[i] is null

I clicked Fix my save and it appears to have fixed the problem.  No issues on my end now at this point but thought I'd log a ticket to let you know this occured.

**Comment by Lazzil** [comment]
Commenting here to report the same issue. My game loaded fine when I first logged in, but the loading window was stuck for me when I switched back to the tab with the experimental setting enabled. I refreshed the page to try to fix it and then got the same error message. The "Fix my save" worked for me as well. I was fishing manta rays on my alt account at the time.

**Comment by GeneReyva** [comment]
Commenting because I am now having this issue. It happened to me when I looted a load of stuff after killing Goo Monsters.

Skip a few minutes, I tried enabling that experimental setting (after canceling loading a save and logging off), refreshed, fix save, fix save, load local and it worked for me. So that might be a fix. Thanks Lazzil.

**Comment by TheMalcs** [comment]
This has been hotfixed. Let me know if you run into issues,

**Comment by MelvorIdle** [comment]
This should be hotfixed. Let me know if you run into further issues,
