### ISSUE TITLE
Township easy task

### ISSUE THREAD

**Issue by Zhoie** [MelvorIdle/melvoridle.github.io#2925]
### Describe the bug

This task needs bird nest potion I, but what my master level already up to 50 I can not produce bird nest potion I anymore but bird nest potion III.

### Screenshots

![9B489E14-E7C5-40D7-BC8E-093ABCA79819](https://user-images.githubusercontent.com/11780853/200205286-dedce6f6-22e4-4fd6-bff3-7cfd5006e23f.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by Delerium** [comment]
It's hard but not impossible. You need to use the herblore potion to produce tier 1 potions randomly.  Though I do agree that this township 'easy' task is way too difficult if you have passed up tier 1 potions for those you need to turn in.

**Comment by sirPattrick** [comment]
I don't believe this should be closed.   Unless something has truly been addressed that will fix this in a future update.   This quest should allow any tier birds nest potions to complete.   Then a follow up Normal Difficulty Quest could be for a T2+ potion, a Hard Quest for a T3+, Etc.   This is really frustrating that I will not be able to complete this "Easy" Quest until I level up my Herblore to 71, so I can make the "Herblore Potion", and then still have to wait for dumb luck, in order to possibly get the 25 of each of the potions to complete it.
