### ISSUE TITLE
[Bug]: Meteorite HP Missing

### ISSUE THREAD

**Issue by AnUnsafeTaco** [MelvorIdle/melvoridle.github.io#3022]
### Describe the bug

I finally unlocked the ability to mine meteorite ore, and none of my built up HP is there. I have maxed out Astrology to level 120 including mastery. 

### Expected behaviour

I expected to see some HP on the Meteorite Ore node in Mining, as I have maxed out Astrology and have a bunch of Meteorite HP built up.

### Save Link

https://melvoridle.com/save/bsOYTjUG

### Screenshots

![Screenshot_20221122-131308](https://user-images.githubusercontent.com/118849647/203403324-3edbaa7b-a642-4555-95e0-720510221eb3.png)
![Screenshot_20221122-132417](https://user-images.githubusercontent.com/118849647/203403496-22d114a2-c7ea-4fb3-9d44-a036d9bf88b5.png)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4908

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This issue was due to the expansion data failing to load, but still allowing you to load in a save resulting in lost save data. Unfortunately we are unable to recover this data. This was fixed with v1.1.1 (?5023). It should no longer be possible to load a save if expansion data fails to load due to networking (or other) errors.
