### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by Wavidditmer** [MelvorIdle/melvoridle.github.io#3071]
### Describe the bug

All superior gem veins and meteorite ore vein went to 0. 

### Reproduction Steps

Unknown, booted up the game and no longer had anything in any of the veins 

### Expected behaviour

I expected to see 18000+ meteorite ore and onyx gems in the veins, and around 1000 Oricha. However I see 0

### Screenshots

![BFDBEE4A-32BB-487E-86CF-FA8A22C61236](https://user-images.githubusercontent.com/119959787/205969159-0ac76617-aabe-481d-8981-649cae88fb9d.png)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?4937

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This issue was due to the expansion data failing to load, but still allowing you to load in a save resulting in lost save data. Unfortunately we are unable to recover this data. This was fixed with v1.1.1 (?5023). It should no longer be possible to load a save if expansion data fails to load due to networking (or other) errors.
