### ISSUE TITLE
[Bug]: Game reset itself 

### ISSUE THREAD

**Issue by Mick2712** [MelvorIdle/melvoridle.github.io#3121]
### Describe the bug

My game crashed and went straight to the menu, and when i logged in again all equipment sets empty and the equipment was back in my bank, in golbin raid all equipment and food was gone and had disappeared, and in farming it said crops was ready, but wasnt able to harvest and all gem veins and meteorite vens was at 0

### Reproduction Steps

The app crashed/ closed down so can’t reproduce

### Expected behaviour

Could harvest again after closing and reopening the app, golbin raid i didnt care about but if my gem vein/ meteorite ore healt could be restore i’d be happy, but it happend over a week ago, and play’d alot since so not sure if anything can be done?

### Save Link

https://melvoridle.com/save/etAUW8Ug

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

(?4999)

### Are you using any mods?

No

**Comment by coolrox95** [comment]
This issue was due to the expansion data failing to load, but still allowing you to load in a save resulting in lost save data. Unfortunately we are unable to recover this data. This was fixed with v1.1.1 (?5023). It should no longer be possible to load a save if expansion data fails to load due to networking (or other) errors.
