### ISSUE TITLE
[Bug]: <title>Bug]: Knight's Defender doesn't lower attack speed in Golbin Raids

### ISSUE THREAD

**Issue by Gorysporkman** [MelvorIdle/melvoridle.github.io#3227]
### Describe the bug

The Knight's Defender in Golbin Raids doesn't give an improvement to attack speed.

### Reproduction Steps

1: Enter a Golbin raid
2: Obtain a Knight's Defender in the offhand slot or passive slot

### Expected behaviour

Attack speed should be decreased by 0.05 as the item itself grants 0.1s which is halved in golbin raids.

### Save Link

https://melvoridle.com/save/m4JGauKS

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

No

**Comment by MelvorIdle** [comment]
This is only a visual bug due to the game's tick system (actions occur every 0.05s), the rounding of the final attack speed, and how Javascript cannot handle float value equations well at all.

The attack speed is changing, it just isn't visually displayed. Not something we can fix unless the attack speed difference is >0.1s
