### ISSUE TITLE
[Bug]: <title>3rd Character stops working

### ISSUE THREAD

**Issue by RogueSeraph0257** [MelvorIdle/melvoridle.github.io#3238]
### Describe the bug

Doing Mole Tablets, have 50K+ Green Shards and 100k Dragonite ore, plenty Necro Potions, but every time I go back to him/her/it they have stopped producing. Anyone else having this issue?

### Reproduction Steps

start game,
Select 3rd Character,
go to Summoning
See it isn't producing when it was when I left

### Expected behaviour

Character is still working

### Save Link

https://melvoridle.com/save/ZhBHTlKr

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

4999

### Are you using any mods?

No
![Melvor 3](https://user-images.githubusercontent.com/126624504/222008251-e715ca9a-5573-40db-a3d1-e5c1993ef974.jpg)

Just told me I didn't have the required materials

**Comment by MelvorIdle** [comment]
Your Bank is full, so the game stops the current Skill when an item cannot fit. This is caused by global rare items you are receiving while training, causing the Skill to stop.

Enabling this setting will allow you to train without stopping the skill if an item cannot fit: https://i.imgur.com/eLT19Eb.png
