### ISSUE TITLE
[Bug]: Mastery achievement error

### ISSUE THREAD

**Issue by warmkor** [MelvorIdle/melvoridle.github.io#3256]
### Describe the bug

I know that the steam achievements can be unlocked based on the basic game process without the DLC. 
I reached 100% masteries in all non-combat skills, but my 100% Mastery achievement is still unlocked.
In addition, in the attached screenshot, you can find that the cooking mastery level is over 100%, which is weird.
I unlocked all achievements except this, so I really want to achieve it as soon as possible.

### Screenshots

![error](https://user-images.githubusercontent.com/127378624/223935059-b2c61ecb-7c0d-4a87-bb60-74eedfe68dcd.JPG)
![error2](https://user-images.githubusercontent.com/127378624/223935063-dd91b80f-ac8c-4875-9b88-13d3d7a290d5.JPG)
![mod](https://user-images.githubusercontent.com/127378624/223935396-313c6b73-7f82-4773-a5db-4efb4465aefa.JPG)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.1

### Game Subversion

?5053

### Are you using any mods?

Yes

**Comment by gawkydotcc** [comment]
Regarding the cooking mastery going over 100%, it is because the Lemon Cake cooking recipe has a mastery associated with it.
When cheating mastery levels, filter out CookingRecipe object with the id of **melvorF:Lemon_Cake**.

As for the achievements, they are loaded after your character is loaded, so next character load the mastery achievement will be unlocked. Alternatively, use this function to unlock it mid game:
`parent.greenworks.activateAchievement(NEW_ACHIEVEMENT_1_4, () => {});`
Or you can use my achievement manager mod https://mod.io/g/melvoridle/m/achievements.
There is also the Steam Achievement Manager available here on GitHub.

**Comment by warmkor** [comment]
> Regarding the cooking mastery going over 100%, it is because the Lemon Cake cooking recipe has a mastery associated with it. When cheating mastery levels, filter out CookingRecipe object with the id of **melvorF:Lemon_Cake**.
> 
> As for the achievements, they are loaded after your character is loaded, so next character load the mastery achievement will be unlocked. Alternatively, use this function to unlock it mid game: `parent.greenworks.activateAchievement(NEW_ACHIEVEMENT_1_4, () => {});` Or you can use my achievement manager mod https://mod.io/g/melvoridle/m/achievements. There is also the Steam Achievement Manager available here on GitHub.

Thanks, gawkydotcc.
I understand why this happens to me.
Following your suggestion, I can solve my issue.
Thanks again.
