### ISSUE TITLE
[Bug]: mastery magnets are spending but not rewarding any mastery tokens. 

### ISSUE THREAD

**Issue by ihariibo** [MelvorIdle/melvoridle.github.io#3404]
### Describe the bug

When I equip mastery magnet in the consumable slot and use any skill, it uses one magnet per action, but it does not reward any tokens. 

### Reproduction Steps

Equip Mastery magnets
Go to any skill 
Perform said skill
Watch as magnets are spend 
And mastery tokens are not given

### Expected behaviour

1 magnet spent per action
 1 token awarded per action

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by WoneTooPhree** [comment]
The magnet give +1 token when you get a token. 
It will still consume a charge for every action.

**Comment by d3aths** [comment]
i have the same problem. ive probably gone through about 10k of the mastery magnet items now and have only ever received 1 mastery token when gaining a token. i suspect actually my mastery token drop rate may be bugged because i only ever receive 1 mastery token even if leaving my skills running for 12 hours+. and this is in skills where i have a high amount of mastery levels in many items, like were talking 75+ in everything. always only get 1.

**Comment by coolrox95** [comment]
As previously stated, the Mastery Magnet only increases the quantity of mastery tokens received when you actually roll to get one. I am also unable to reproduce any issues relating to this effect not working.
