### ISSUE TITLE
[Bug]: Mastery completion listing over 100%

### ISSUE THREAD

**Issue by Avallach160** [MelvorIdle/melvoridle.github.io#3410]
### Describe the bug

Recently got base game and ToH to 100% masteries. Game's calculating it as > 100% and while it doesn't seem to affect anything in game it does appear to not trigger steams Mastery Master achievement.

Occurred while running mods but still happened after disabling all but 1. Won't let me turn off Expansion Summoning Recipes without corrupting the save.

Mods:
SEMI Core
Unlimited Offline
SEMI Drop Chances
Right Click Equip Menu
QuickShards
Potion Downgrade
Mastery Pool Can Overflow
ETA
Item Uses
Combat Simulator Reloaded
Bypass Agility Costs

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/JHayBIQ8

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/6992987/c40f7566-f8e3-4b42-a07c-83ed69a61bbf)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/6992987/a89a4d7d-50ab-413c-8ed3-40f3a28ee65b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

Yes

**Comment by coolrox95** [comment]
This issue is due to mods (typically SEMI Auto mastery) erroneously leveling the mastery of the Lemon Cake recipe in Cooking. This is not possible through normal game play. 

You can manually fix your save file by using the following console command:
`game.cooking.actions.filter((i) => i.hasMastery !== undefined && !i.hasMastery).forEach((i) => game.cooking.actionMastery.delete(i))`
and then reloading the game.
