### ISSUE TITLE
[Bug]: Mastery pool Fishing EXP discrepancy

### ISSUE THREAD

**Issue by N01UNo** [MelvorIdle/melvoridle.github.io#3438]
### Describe the bug

Mastery pool exp giving from fishing does not match the stated number, usually giving less than stated by more than half. Also, somehow giving less pool exp at higher mastery. 

### Reproduction Steps

Fish. 
get fish.
get wrong mastery pool exp?

### Expected behaviour

Fish. 
get fish.
get stated mastery pool exp

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5911

### Are you using any mods?

No

**Comment by 04Slash** [comment]
The Mastery xp calculation includes action time. Fishing doesn't have a static action time. The action time is a range between 2 values. Due to this, the given mastery exp will vary depending on exactly how long it took to catch the fish. The mastery value shown uses the average time and thus should be the average mastery exp you gain per action over time.

Mastery Pool exp is just 25% of the mastery exp so this will also vary.

**Comment by cocowitt24** [comment]
I noticed the same thing, but I don't think it's just the varying action times. The listed mastery pool XP is about 3x higher than it should be based on the listed mastery XP. For example my current Cave Fish mastery XP is 881, but the pool XP is 667 instead of 220.

![2023-07-13 13 16 16](https://github.com/MelvorIdle/melvoridle.github.io/assets/139094939/7d0227be-991e-4be3-ad8e-dc38854f6a45)
It looks like it's just a visual bug, as the XP being added to the pool is around the expected value. Also, yes I have mods on, but the value doesn't change when I turn all mods off.
