### ISSUE TITLE
[Bug]: Township Population is Incorrect

### ISSUE THREAD

**Issue by aburkett1** [MelvorIdle/melvoridle.github.io#3448]
### **Summary:**
The overall population of my township is not equal to the combined housing numbers of my various biome buildings.

### **Resource Bar:**
![309ff337598b45e52e23e6253376404d](https://github.com/MelvorIdle/melvoridle.github.io/assets/55775300/42a69ac7-9adc-47ab-9510-6b144234149c)

### **Housing:**
**Grasslands:**
![51d92fbff12f18c4414dd6112192ea62](https://github.com/MelvorIdle/melvoridle.github.io/assets/55775300/245143eb-bc79-42ee-8862-e255b4ba43e5)
**Arid Plains:**
![073f0cbc5a303891fc2d11eba39a1fe6](https://github.com/MelvorIdle/melvoridle.github.io/assets/55775300/2cdb8c7a-2c22-4377-8a58-54500a21529b)
**Snowlands:**
![37e72aa1c41852cbb392c4a703ebb4b4](https://github.com/MelvorIdle/melvoridle.github.io/assets/55775300/d66c861a-f2a2-4372-b9a0-e6b2a92274c5)

I'm not sure how this number is being calculated and it seems like something is off.

### Expected behaviour

I expect the total population to be the combined housing number multiplied by happiness percentage increase times health.

**Formula:**
(h1+h2+h3) * Happiness * Health

**Hypothesized:**
(9,360+14,070+18,720) * 1.285 * 1 = 54,162.75 population

**Actual:**
17,900

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/MyYZu5qz

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?5916

### Are you using any mods?

No

**Comment by mythridium** [comment]
@aburkett1 

You've got the bug backwards, the total population is actually correct, but the individual tiles are reporting incorrect values.

The individual tiles count the total number of buildings across all biomes instead of just their own biome, so the count gets inflated as it counts buildings more then once. It is merely a display bug on individual tiles.

I actually wrote a mod which patches the function and fixes the issue: https://mod.io/g/melvoridle/m/myth-township

Would be good for this to be officially resolved though so my mod isn't needed.
