### ISSUE TITLE
[Bug]: Agility obstacle overwritten/can’t delete

### ISSUE THREAD

**Issue by npmd18** [MelvorIdle/melvoridle.github.io#3508]
### Describe the bug

Obstacle 1 cannot be accessed, it appears as:
Obstacle 4
Obstacle 2
Obstacle 3
Obstacle 4
Clicking it shows obstacle 4 information. 
Attempting to delete the obstacle does nothing.
I can’t use obstacle 1 now.

### Expected behaviour

To be able to use obstacle 1

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/R4eOR9l8

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6126

### Are you using any mods?

No

**Comment by 04Slash** [comment]
After making a backup, you should be able to fix this with `game.agility.builtObstacles.delete(0); game.agility.renderQueue.builtObstacles = true`. Since you're on mobile, you will need to use the dev.console mod to paste the above into (or load your save onto a browser and hit f12).

Your blueprint has obstacle 4 in slot 1. While loading this blueprint won't cause this issue again (from my test), it will cost materials and won't build the obstacle so I'd probably avoid using it.

**Comment by npmd18** [comment]
Thanks for the quick response, this worked for me. I appreciate your help!
