### ISSUE TITLE
[Bug]: Carrot cake not going into inventory

### ISSUE THREAD

**Issue by ClipClopBoom** [MelvorIdle/melvoridle.github.io#3520]
### Describe the bug

Trying to make perfect carrot cakes for the township task. Active cooking uses resources/builds mastery, but the items disappear into the ether, both normal and perfect.

There’s space in my bank so that’s not the issue.

### Reproduction Steps

1) Select cooking > furnace > carrot cake
2) Select active cook

### Expected behaviour

Items should go to inventory during active cook

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/B1miUHRN

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.2

### Game Subversion

?6153

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
The food is going directly into your food slots because you've purchased [Cooking Upgrade 1](https://wiki.melvoridle.com/w/Cooking_Upgrade_1)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/01fc7bf0-5146-4140-bbe4-83889d2d43d2)
If you want the food to go directly into your inventory, disable this on the cooking page:
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/4c55fd84-8d33-4bb7-949c-9123eac0a113)

**Comment by ClipClopBoom** [comment]
Well I feel stupid :/ in my defense I’ve only played intermittently for months and forgot that upgrade was a thing. Closing.
