### ISSUE TITLE
Can start and fight dungeons in golbin raid

### ISSUE THREAD

**Issue by dariof4** [MelvorIdle/melvoridle.github.io#355]
**Describe the bug**
You can select to fight a dungeon (or regular mob) while doing the golbin raid, this makes it so you fight it, but the enemies are the golbins you normally face in the golbin raid, if you beat a dungeon this way you gain the rewards you would normally get from beating the dungeon.

**To Reproduce**
1. Go to goblin raid
2. Click start the raid
3. Click on browse dungeons (or any other mob)
4. Start any dungeon (or any other mob)
5. See error

**Expected behavior**
You shouldn't be able to fight mobs or dungeons while doing golbin raid.

**Screenshots**
(The buttons to choose a dungeon/mobs appear on the golbin raid page)
![2020-08-17_12-56-42](https://user-images.githubusercontent.com/9992814/90389061-2559b980-e089-11ea-9270-a3e4130cb95b.png)
(Me doing volcano while in golbin raid)
![2020-08-17_12-57-48](https://user-images.githubusercontent.com/9992814/90389124-47ebd280-e089-11ea-8350-0e648f74e87c.png)
(Me fighting a scattered goo monster in golbin raid)
![2020-08-17_13-03-13](https://user-images.githubusercontent.com/9992814/90389537-09a2e300-e08a-11ea-91ad-5b66fb0538d0.png)

**Browser**
Firefox 79.0 (64 bit)
Chrome 84.0.4147.125 (64 bit)

**Console output**
I don't think it's needed for this.

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
Hotfixed

**Comment by TraDukTer** [comment]
I just got a similar bug today. Instead of going into the golbin raid and then starting the dungeon, I started the golbin raid with the dungeon started. The game gave a warning, removed me from the dungeon and moved me to train on golbins in the golbin village:

![image](https://user-images.githubusercontent.com/57787752/111473090-54c1c900-8733-11eb-99cc-68df0dfbf4a8.png)

Which seems like a deliberate fix, but the loadout is still logged in the raid history as a golbin raid:

![image](https://user-images.githubusercontent.com/57787752/111473240-7e7af000-8733-11eb-9b3f-cc27b4c09acd.png)

(top and 3rd highest are bug-related, if that wasn't clear)

I'm playing in browser (FireFox)

Steps to reproduce:

1. Start a dungeon
2. Go to Golbin Raid
3. Click on Start the Raid
4. See Raid History
