### ISSUE TITLE
[Bug]: Swapping Quick Equip consumables leaves 1 item in inventory

### ISSUE THREAD

**Issue by datcactus** [MelvorIdle/melvoridle.github.io#3607]
### Describe the bug

When switching between two consumable items the item being equipped will always leave 1 of itself in the bank. This takes up a bank slot unnecessarily and seems like a range is being referenced incorrectly somewhere given the 1 item left behind behavior.

### Reproduction Steps

1. Set two consumables in quick equip (using Looter Pouch and Melee Hinder Scroll in my testing)
2. From quick equip, equip whichever item is in the bank
3. Observe that 1 item is left behind
4. Observe that swapping between items leaves 1 item behind consistently

### Expected behaviour

All items should be equipped, draining the bank slot.

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.2

### Game Subversion

?7747

### Are you using any mods?

No

**Comment by Chrisch3n** [comment]
I have the same bug on iOS 17.3.1 with game version 1.2.2 (no  expansions, no mods).
It's quite annoying.

**Comment by luke-bravenboer** [comment]
Important point of distinction - (for me at least) this **only affects the quick-equip functionality in the equipment sets menu** in the top-right of the screen.

Using the quick-equip gear in the minibar at the lower-right of the screen (for non-combat skills) does not have the same off-by-one issue. So for non-combat skills, the minibar quick-equip menu is a sufficient workaround - this issue is specifically just annoying for combat.

**Comment by luke-bravenboer** [comment]
The issue definitely persists, by the way. Super annoying for quick-equipping consumables in combat mode.
