### ISSUE TITLE
[Bug]: Golden Trowel +8% Mastery Bonus Description Incorrect - It reduces the Mastery XP amount  

### ISSUE THREAD

**Issue by emu1972** [MelvorIdle/melvoridle.github.io#3910]
### Describe the bug

The Golden Trowel's description states a +8 Mastery Bonus.  
When equipped.  The Mastery Bonuses for each dig site is reduced by at least 8%

### Reproduction Steps

1, Select Select The Archaeology Skill.  
2. Observe Mastery XP for any dig site.
3. Equip the Golden Trowel.
4. Observe the same Mastery XP.  
Result:  Notice the Mastery XP is reduced with the Golden Trowel equipped.  

### Expected behaviour

Either 
1.  The description reads as a negative modifier reflecting the % deducted.  
or
An increase in the Mastery XP reflecting the modifier's positive value.  

### Screenshots

![Melvor Idle Golden Trowel Equipped - Mastery XP](https://github.com/MelvorIdle/melvoridle.github.io/assets/7507107/d3a07fd7-0c1c-4b6e-b0f6-f2405065a0a9)
![Melvor Idle Golden Trowel Unequipped - Mastery XP](https://github.com/MelvorIdle/melvoridle.github.io/assets/7507107/629029bc-8449-41f7-b475-1308c93931ea)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8160

### Are you using any mods?

No

**Comment by 04Slash** [comment]
The mastery calculation includes Interval Time. [You can see the formula on the wiki](https://wiki.melvoridle.com/w/Mastery#Earning_Mastery_XP). This will result in the mxp for Gathering type skills (skills that don't require any resources to train) to always remain the same regardless of what your interval time is.

If we do the math for the experience over time instead of looking at the raw number, we can see that using the Trowel results in more mxp per second than not using the Trowel.

With Trowel: 610mxp/2.85s = 214.03mxp/second
Without Trowel: 671mxp/3.25/s = 206.46mxp/second
