### ISSUE TITLE
[Translation Error]: <Goblin Raid> Chinese

### ISSUE THREAD

**Issue by EinProfispieler** [MelvorIdle/melvoridle.github.io#3926]
### Which text in the game has a translation error?

哥布林 副本
goblin raid

**Comment by VariableVictor** [comment]
I agree. All of the word "goblin" in the game should be translated to Chinese word "哥布林“ rather than "戈耳宾”.
![Snipaste_2024-01-26_16-42-16](https://github.com/MelvorIdle/melvoridle.github.io/assets/22555507/b0b1615f-d340-46c5-9db6-2e62d42fe038)
![Snipaste_2024-01-26_16-43-05](https://github.com/MelvorIdle/melvoridle.github.io/assets/22555507/bc157d5b-0cb4-478d-8f36-cf36170587e5)
![Uploading Snipaste_2024-01-26_16-43-55.png…]()

**Comment by EinProfispieler** [comment]
either mismatch on acoustic nor regular player understanding.
