### ISSUE TITLE
Pets

### ISSUE THREAD

**Issue by mrDLSable** [MelvorIdle/melvoridle.github.io#40]
Basically, I want pets. Pets will of course need pet food a couple of times a day. Which can be bought from the store. If you run out of pet food the pet dies. Every pet that you have requires pet food. This would introduce a scaling gold sink.

Pets give a small bonus. For example, a phoenix might give a 5% xp bonus to firemaking. But in my mind pets are mostly just a collection thing.

**Comment by mrDLSable** [comment]
A pet duck rescued from the Kraken, called the Quacken.

**Comment by Shantel444** [comment]
I have a dog. I love her very much and can't imagine my life without her. It has to be noted that it is important to take care of your pet in a proper way. Usually I order meds for my dog on a [Pet Pharmacy](https://www.worldpetexpress.net/) site. I chose it because of wide range or products and affordable prices. Maybe this source will be useful for you.

**Comment by mrDLSable** [comment]
@Shantel444 are you alive or a spam bot?

**Comment by Eusmusia** [comment]
From my previous post, combat pets could drop from their respective boss and give a small combat boost, such as a damage increase or melee str increase, and if magic is added, some new pets could offer magic bonuses.

Pets could be obtained from a variety of different ways such as getting the "Giant Shark" from Fishing, the "Phoenix" from firemaking, etc. These pets would give bonuses in their respective skill, as mrDLSable mentioned above.

Pets would either need to be in the bank or equipped like an item in order to gain the bonuses.
