### ISSUE TITLE
[Bug]: Palladium Onyx Necklace doesn't work

### ISSUE THREAD

**Issue by TaurusAlpha** [MelvorIdle/melvoridle.github.io#4018]
### Describe the bug

Palladium Onyx Necklace sometimes doesn't give passive Slayer Coins. It works for some creatures and for some doesn't

### Reproduction Steps

1. Equip Palladium Onyx Necklace
2. Got Slayer task for Druid and Master Wizard
3. Check for coins income. Got only creature HP Slayer coins amount

### Expected behaviour

Slayer coin income should be HP and creature combat level.
Got correct amount for Rune Knights for example

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8287

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Palladium Onyx Necklace works specifically for Melee targets which is why it worked for Rune Knights and not Druids and Master Wizards.
You want the Palladium Runestone Necklace for Magic Slayer task monsters and Palladium Oricha Necklace for Ranged Slayer task monsters.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/a58ed598-3591-4b6e-9999-903a60fbf60f)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/62bd49d3-a2b4-47f5-91e7-129f17e8540a)
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/57328541/92b682cc-5b0a-46f1-b20a-4e8e5f0b821a)

**Comment by TaurusAlpha** [comment]
Then it's translation bug. In Russian translation it doesn't specify for which kind of creature it works. Thank you for clarification.
