### ISSUE TITLE
[Bug]: Died Twice on Reload

### ISSUE THREAD

**Issue by hanacker** [MelvorIdle/melvoridle.github.io#4040]
### Describe the bug

Was farming Alarune on Android app, game restarted itself, and when I loaded back in, I died. Happened twice. Auto-eat threshold was above max hit while asleep and I hadn't died in an hour of farming it before the restart.  Prayer point, summons, and food were good. Other people on Discord reported similar issues. 

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8363

### Are you using any mods?

Yes

**Comment by mythridium** [comment]
@MelvorIdle Some additional context on this one.

This happens because of `applyReductiveEffect` calls `computeCombatStats`.

Inside `computeCombatStats` it computes the max HP which uses `levels.hitpoints`, but this doesn't get set until `super.computerAllStats`.

Use the following save file, go into combat with Rokken, then reload the game to reproduce.
[dead-save.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/14105482/dead-save.txt)

HP correctly decoded and set as expected.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/308d3784-34c7-40d7-a9ba-a30d0a5d7faf)

Compute all stats is called during initialization which checks item effects.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/0ab85c4d-63c1-4837-8e64-76d65764195f)

`checkItemEffects` calls to compute the combat stats.

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/71e303bc-020c-4520-a5e9-e2ea3d01e854)

But because the hitpoints levels don't get calculated until `super.computeAllStats` is called in the line after in the first image, it resets the hp to 10.
![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/10d6de0a-85b7-48c4-9d4b-e5ecaf1f409f)

I think the solution is to either move `checkItemEffects` after the `super.computerAllStats` in player.js OR call `computeLevels` just before `computeCombatStats` inside `checkItemEffects`

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/132613374/7df10afe-76a9-4b1c-8b34-7e6bf509c55d)

**Comment by MelvorIdle** [comment]
A hotfix has now been pushed to the live game. Thanks for the report and also thanks for the very detailed breakdown @mythridium , really appreciate it!
