### ISSUE TITLE
Trouble with some inventory actions

### ISSUE THREAD

**Issue by Gailbear** [MelvorIdle/melvoridle.github.io#4051]
### Describe the bug

I can't seem to equip things to my quiver or use the mastery tokens I just got. This seems to be a new issue? I can open chests I acquired a few days ago. I tried force closing the app and also changing characters. 

The behavior is: I open up the inventory item, I press the yellow button, and it looks like I pressed it, but nothing happens. If I click on something else in my inventory and then try to click the item that didn't work again, it doesn't open anything - I have to click it a second time to open the inventory item.

I haven't tried selling my mastery tokens for the sake of debugging because this is my actual account, heh.

### Reproduction Steps

1. Go to the bank
2. Click on the mining mastery tokens to open the inventory screen
3. Click claim token
4. Nothing happens

### Expected behaviour

I expected to be able to claim the mastery tokens

### Save Link - Required if issue occurs with a save

https://melvoridle.com/save/Aooo1Gzg

### Screenshots

This is what the button looks like after I press it
![Screenshot_20240201-232002](https://github.com/MelvorIdle/melvoridle.github.io/assets/634425/cc89a064-a6b8-4ae1-be5b-76a2aef0c028)

This is what the bank tab looks like when I go back to it (note the green border)
![Screenshot_20240201-232007](https://github.com/MelvorIdle/melvoridle.github.io/assets/634425/4e1062ef-9fdd-409e-98df-fe211b8bad34)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [ ] Throne of the Herald
- [ ] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8381

### Are you using any mods?

No

**Comment by 04Slash** [comment]
Your Mining mastery pool is currently 100%. This will prevent tokens from being used since the mastery XP will all go to waste.

As for equipping things to the quiver, you currently have no ammo in your bank that can be equipped with your current Ranged skill level. Adamant Arrows require Ranged level 30 and Rune requires level 40.

**Comment by MelvorIdle** [comment]
Thanks for the report, and thanks for the information Slash.

It looks like the real bug here is in fact the notifications. They seem to be hidden behind the bank item popout, so it seemed like nothing was happening when in fact the game was trying to tell you what was wrong (but you couldn't see it).

I'll action to get this fixed.

**Comment by Gailbear** [comment]
> Thanks for the report, and thanks for the information Slash.
> 
> It looks like the real bug here is in fact the notifications. They seem to be hidden behind the bank item popout, so it seemed like nothing was happening when in fact the game was trying to tell you what was wrong (but you couldn't see it).
> 
> I'll action to get this fixed.

Ah yeah! That explains it! Good to know I'm not just missing something obvious!

**Comment by MelvorIdle** [comment]
This issue has now been hotfixed.
