### ISSUE TITLE
[Bug]: Big Ol Ron Not Calculating DR in Offline Combat

### ISSUE THREAD

**Issue by Torun-S** [MelvorIdle/melvoridle.github.io#4078]
### Describe the bug

The Combat Simulator would tell me that I should not die to a Rokken at all (after 100 000 trials), and observing actual combat with the same equip, its max hit doesn't surpass my Auto-Eat threshold even while stunned, and I left the game running for close to an hour without death.

Soon as I log off for 90 minutes and return, I die. I repeatedly loaded from the Cloud, and died on over 10 reloads. I then online combat for another half hour without a single death again.

Me and another user experience this sudden death, and our common element seems to be having the Big Ol Ron. It's likely its DR doesn't get calculated in offline and our max hit is pretty close to the threshold with it on.

### Reproduction Steps

1. Wield Big Ol Ron.
2. Prepare for combat so that your Auto-Eat is close to Rokken's Max Hit on stun.
3. Observe combat to ensure it is idleable, or use Combat Sim
4. Let it run with game open for a period of time, observe no deaths
5. Log off and return after some time
6. Observe death on load

### Expected behaviour

The outcome in online combat should match the outcome of offline combat.

### Screenshots

![image](https://github.com/MelvorIdle/melvoridle.github.io/assets/117641290/fd8a7f69-c23e-4d7f-aa73-2701e70c522b)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Steam
- [ ] Epic Games
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8417

### Are you using any mods?

Yes

**Comment by Modddder** [comment]
I'm the other user mentioned in this thread. Similar thing happened to me, except on hardcore so i lost my save file. Here's the screenshot of my  combat sim
![aeris_god](https://github.com/MelvorIdle/melvoridle.github.io/assets/33007122/d5c556eb-7261-4c45-8e0d-240548cece33)
The only monster that was able to (and did) kill me, was the Aleron monster. With base 43% dr that I had, he can kill me but since I had big ol ron, his passive gave me extra 2 dr which puts me at 45% which is exactly how much I need to live this dungeon, but haven't due to big ol ron's passive not working offline. I'd appreciate if there's any way to get my exact save file back, since I won't be able to remember everything I had on my hardcore account and re-add it to my older save file.
