### ISSUE TITLE
[Bug]: Unable to launch game

### ISSUE THREAD

**Issue by Jack-Bruce-Dev** [MelvorIdle/melvoridle.github.io#4135]
### Describe the bug

Load game and login via last cloud save. Game loads but cannot click anything or play the game

### Reproduction Steps

Launch game
Sign in

### Expected behaviour

Able to play game normally 

### Screenshots

![IMG_1319](https://github.com/MelvorIdle/melvoridle.github.io/assets/92029623/0b51360c-4ece-412c-8e9c-27ab3681c105)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

Not visible on iOS 

### Are you using any mods?

Yes

**Comment by 04Slash** [comment]
Are you using automation mods (SEMI, Action Workflows), speed mods/gamemodes, and/or Multitasking? This problem almost always stems from using those types of mods because they increase the amount of calculations that have to be done while offline, increasing the time it takes to load the save.

The save should load eventually (would be faster on a PC). Otherwise, if you don't wish to wait, disabling the mods should make the save load quickly.

**Comment by Jack-Bruce-Dev** [comment]
@04Slash turned everything off… still stuck at the same point
