### ISSUE TITLE
Some banked items quantity decrease

### ISSUE THREAD

**Issue by Gormador** [MelvorIdle/melvoridle.github.io#448]
**Describe the bug**
Some banked items randomly (probably not, but can't reproduce) get a negative count. Selling them nets a negative amount of GP.

**To Reproduce**
Can't reproduce. Seems to happen on random drops (currently sitting on -14 diamonds). Not the first item it happens to, previously sold a negative amount (can't remember the specifics) of an item to test if my GP would decrease and had to catch up on a ~ -7kGP.

**Expected behavior**
Items quantities shouldn't be able to drop below 0.

**Screenshots**
Negative quantity:
![image](https://user-images.githubusercontent.com/6118753/96293137-9286be00-0fea-11eb-970b-9fd32cf1c974.png)
Reflected into the bank value:
![image](https://user-images.githubusercontent.com/6118753/96293210-b34f1380-0fea-11eb-82f7-c275faa5f35a.png)

**Browser**
Google Chrome (on Ubuntu), Version 85.0.4183.83 (64 bits)

**Console output**
Warnings & Errors:
[melvoridle.com-1602871870424.log](https://github.com/MelvorIdle/melvoridle.github.io/files/5393550/melvoridle.com-1602871870424.log)
Everything:
[melvoridle.com-1602871970867.log](https://github.com/MelvorIdle/melvoridle.github.io/files/5393554/melvoridle.com-1602871970867.log)

**Are you using any scripts?**
N/A

**Comment by Gormador** [comment]
**Update**
Just witnessed an my Emerald amount go from -1 to -3.
Current occupation is fishing. It may have happened when getting a random fishing drop which filled my bank, but not sure.
Will try and see it happen again and provide another update.

**Comment by Gormador** [comment]
**Update**
Happened again on Bones.  
And I _think_ (not sure) the amount decreased of the amount of feathers I just sold. And it _may_ have decreased upon arrow hover? I have no certainty in any of this, just trying to provide with what I think I'm witnessing happen.

Will kill some chickens and try to reproduce.

**Comment by lucidobservor** [comment]
I'll add my own account of this bug:

- This is a fairly new game
- A few days ago, I acquired one, and only one, Tomato Seed from a Bird Nest. This single tomato seed has been sitting alone in a bank tab since then.
- Today I checked my bank and saw that I had -20 Tomato Seeds. 

I made a bug report of a separate bug earlier today, and it actually seems related to this one: #447

**Comment by MelvorIdle** [comment]
Definitely looking for steps to reproduce so I can get a hotfix out ASAP for it

**Comment by ERonayne** [comment]
I ran into this bug as well. I'm currently unable to reproduce as I did not see my item quantity decrease live. I just noticed I had -3 Chapeau Noir. I used to have 3. I'm not sure when it happened but I have not gained any Chapeau Noirs or done any thieving since 0.17 came out. It was the last item in one of my bank tabs. Although, the next item in my bank would be the first item in the tab to the right. That would have been blue d hide which I did recently use up entirely making blue d hide bodies. Interestingly, blue d hide bodies also require 3 blue d hide to craft, which could take the three Chapeau Noir count from 3 to -3 with 2 crafts. Perhaps it is some sort of index off by one error/two different arrays not in the same order.

**Comment by MelvorIdle** [comment]
I have just released a hotfix for this. I managed to reproduce the bug 100% so hopefully I have sourced the exact cause.

**Comment by Gormador** [comment]
> I have just released a hotfix for this. I managed to reproduce the bug 100% so hopefully I have sourced the exact cause.

Thanks a lot and congrats, didn't look like an easy one.
Will stay vigilent and let you know if it happen again.

**Comment by GrrAngry** [comment]
I just had this happen to me. I have no plugins/modifications, Chrome Version 87.0.4280.66.

In my main bank tab, the last three items in order are: 1 Farming Skillcape, several hundred Red Dragonhide, and several hundred Red D-Hide Body

I'm currently crafting the Red D-Hide Body. I alt-tabbed away from Chrome and when I came back, the "while you were away" dialog popped up and showed offline progress. I dismissed the dialog, clicked the bank tab, and just so happened to notice that my Farming Skillcape was sitting on -2 quantity. I immediately equipped it and it disappeared from the bank entirely (it did not go from -2 to -1). When I unequipped the cape, it went back to 1 quantity in the bank.

My assumption is similar to some of the other guesses. There's an off-by-one index error causing the -3 for the Red Dragonhide to be applied to the item next to it. Further, I did have a single Charge Stone of Rhaelyx and a single Mysterious stone, so possibly some combination of inventory re-writing happening before the -3 for the Red Dragonhide gets applied.
