### ISSUE TITLE
Quantity sold bug

### ISSUE THREAD

**Issue by Edotod25** [MelvorIdle/melvoridle.github.io#449]
**Describe the bug**
In the new bank, on statistic page, it says that I sold 1000000000000000000+ Leaping Broad Fish

**To Reproduce**
1. Go to Bank
2. Click on Leaping Broad Fish
3. Click on Statistic 
4. See error --> Quantity sold

**Expected behavior**
152248

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/51761964/96296940-62421e00-0ff0-11eb-9160-71ebb50d43ca.png)

**Browser**
Chrome (Last Version) + Mobile App (Same problem)

**Are you using any scripts?**
Nope

**Comment by CranberrySauce** [comment]
i noticed this problem in the general statistics page. where the total number of item sold number wasn't being added, but the new sold item was being added to the end of the number string
IE: 123 + 4 turns into 1,234 instead of expected 127.
![melvor idle total sold glitch](https://user-images.githubusercontent.com/5732435/96806580-16212000-13da-11eb-9b02-3eb969724292.png)

**Comment by phantomonium** [comment]
![afbeelding](https://user-images.githubusercontent.com/73463012/97145273-3c421980-1766-11eb-92b8-e1a3bc1a06c4.png)
Same, firefox, no scripts
