### ISSUE TITLE
Crashing on Mysterious Figure 1 of Into The Mists Dungeon

### ISSUE THREAD

**Issue by wyattrs** [MelvorIdle/melvoridle.github.io#544]
**Describe the bug**
The game pauses then crashes the browser tab entirely when I spend even five minutes in the fight with the first mysterious figure with my current setup. I have had this happen twice in a row.
**To Reproduce**
I am unsure what is producing the behavior

**Expected behavior**
Seems to crash when she uses the 2.6s Reap attack, alongside my quad swipe spec with the infernal claw as the crash has occurred twice when this attack was beginning loading the spec bar for both myself and the npc
**Screenshots**
![image](https://user-images.githubusercontent.com/40220038/102426611-a300e800-3fdd-11eb-8417-3a60df243f28.png)
this is the setup I was using alongside the piety and stone skin prayers

**Browser**
The most recent version of microsoft edge

**Console output**
I am unable to interact with the tab and generate the report when it has crashed in such a fashion, unfortunately

**Are you using any scripts?**
I am using SEMI

**Comment by MelvorIdle** [comment]
Are you able to confirm if disabling SEMI fixes this issue?

**Comment by TrickleDownEconomics** [comment]
I've had this issue as well. Do you have autorun on? My best guess is that you're actually dying, but autorun locks things up. (This is purely speculation, but:) Autorun calculates possible damages and removes you from a fight that you have the potential to die in (IE out of food and the incoming attack will deal more damage than the health you have left or a special attack can one shot you). The problem is that it doesn't know how to handle Affliction (since it was built for V.17). So when you would die, you're doing something that shouldn't be possible with autorun and thus it freezes everything. I was having the same issue on the browser version so I tried running Into the Mist on mobile and died where normally it would freeze.
