### ISSUE TITLE
'Christmas Cracker' button 'Find a Friend' activates 'A Forgotten Past' item

### ISSUE THREAD

**Issue by JackIsenberg** [MelvorIdle/melvoridle.github.io#595]
****** Bug Description ******

****** Steps To Reproduce ******
1. Navigate to and select item 'Christmas Cracker'
2. Click on 'Find a Friend' button from item description
3. See that dialog window for 'A Forgotten Past' is displayed

**Expected behavior**
Find a friend window action to be displayed, instead of 'A Forgotten Past' dialog window

**Screenshots**
See screenshot below for result:
![image](https://user-images.githubusercontent.com/50328/103191788-3ec70980-48a4-11eb-86ac-2f3d52fbdbf1.png)

**Browser**
- Brave Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)
- No blockers enabled and 'Shields Down'
- 
![image](https://user-images.githubusercontent.com/50328/103191902-b72dca80-48a4-11eb-8657-ddf340c24570.png)

**Console output**
[melvoridle.com-1609133631528.log](https://github.com/MelvorIdle/melvoridle.github.io/files/5745983/melvoridle.com-1609133631528.log)

**Are you using any scripts?**
Not that I know of.

**Comment by JackIsenberg** [comment]
Thanks for the great game! Please let me know if you need anything else!

**Comment by g-crocker** [comment]
Adding some details since I'm also experiencing it...

The cracker was giving its usual message until i tried to open a "Message in a Bottle" (I already had the secret fishing spot unlocked, but did it anyways for some reason).

After I did this, the cracker message is now the same as "Message in a Bottle" and I do not get the bracelet, even if I try to open it at the right time

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
