### ISSUE TITLE
Signet ring half (a) is impossible to get

### ISSUE THREAD

**Issue by melsing** [MelvorIdle/melvoridle.github.io#617]
**Describe the bug**
There is currently an issue with the signet ring half (a). I'm unsure about half (b)

I tested on an alt wearing a gold topaz ring and changed the system date 12 hours forward for six months and after millions upon millions of redwood and yew logs I still didn't get the signet half

**To Reproduce**
Steps to reproduce the behavior
1. Simply run an offline test for an extended amount of time 

**Expected behavior**

Should get signet half a but it is not possible

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.

Mobile and web browser mix

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.

No

**Comment by MelvorIdle** [comment]
Thank you for testing this and confirming. I will look into getting it hotfixed

**Comment by Razorflamekun** [comment]
It's been confirmed on Discord.  https://discord.com/channels/625838709203271680/625840209531240469/797220948725202944

**Comment by ethan-yxchen** [comment]
Hi,
I figured out the cause of this bug. It is because for offline rolling for rare items, the implementation is sampling from a Gaussian distribution to approximate the distribution, but the distribution is actually binomial.

The approximation has very large error when it is close to zero: (1) Gaussian distributes into negatives while binomial has no probability mass for k < 0; (2) Gaussian is symmetric but binomial is skewed.

Because of this, not just the offline signet ring half got much under estimated numbers, anything offline with n*p << 0.1 is affected as well (e.g.Rhaelyx).

I have a suggestion of this fix, based on https://en.wikipedia.org/wiki/Binomial_distribution#Computational_methods

```
function binomial_distribution(n, p, epsilon=0.00001) {
  let marginals = [];
  let sumOfMarginals = 0;

  let marginal = Math.pow(1 - p, n); 
  let odds = p / (1 - p);

  sumOfMarginals += marginal;
  marginals.push(marginal);  
  
  for (let k = 1; k <= n; ++k) {
    marginal *= odds;
    marginal *= (n - k + 1) / k;
    sumOfMarginals += marginal;
    marginals.push(marginal);  
    if ((1 - sumOfMarginals) <= epsilon) {
      break;
      // because this early stop condition, this loop will usually only run less than 3 * n * p times (<10 for signet halves)
    }
  }
  return marginals.map(x => x / sumOfMarginals);
}

function sample_from_binomial(numberTrials, chance) {
  let randNumA = Math.random();
  let binomial = binomial_distribution(numberTrials, chance);
  for (const [index, probabilityMass] of binomial.entries()) {
    randNumA -= probabilityMass;
    if (randNumA < 0) {
      return index;
    }
  }
  return binomial.length;
}
```
I test it in chrome dev console like this and it looks good:
```
let mytest = function(n_runs, f, merge, summary){
  for(let i=0; i<n_runs; i++) { summary = merge(summary, f()); }
  return summary;
};
let f = (totalBaseActions, ringHalfChance) => () => sample_from_binomial(totalBaseActions, ringHalfChance);
let counter = (book, key) => { if (!(key in book)) book[key] = 0; book[key] += 1; return book; }

# results
mytest(100000, f(20 * 1000, dropRingHalfAChance(99)), counter, {})
{0: 90506, 1: 9041, 2: 442, 3: 11}
mytest(100000, f(200 * 1000, dropRingHalfAChance(99)), counter, {})
{0: 36714, 1: 36739, 2: 18498, 3: 6194, 4: 1517, 5: 288, 6: 47, 7: 3}
```
The results pretty much matches the number I calculated with pen and paper.

As a comparison, the Gaussian approximation when n*p ~ 0.1, is terrible:
```
let g = (totalBaseActions, chance) => () => Math.floor(generateGaussianNumber(getMean(totalBaseActions, chance), getStdDev(totalBaseActions, chance)));

#
mytest(100000, g(20 * 1000, dropRingHalfAChance(99)), counter, {})
{0: 62414, 1: 218, -1: 37348, -2: 20}
```
Feel free to take this code snippet and modify in any form, I would like to see the game become awesome. The snippet here is written by myself and I declare CC0 (release into public domain).

**Comment by MelvorIdle** [comment]
Thank you ethan, you saved me a lot of time trying to fix this bug by providing that code.

I can confirm the code works as intended, and I have now hotfixed it into the game. Signet is now possible to retrieve offline.
