### ISSUE TITLE
Many magic skills show combination runes that are the same as regular runes

### ISSUE THREAD

**Issue by Silberdrachi** [MelvorIdle/melvoridle.github.io#646]
**Describe the bug**
Magic skills in the combat window display both combination runes and regular rune sets for skills that have no combination rune option.

**To Reproduce**
1. Go to combat window
2. Click on magic skills
3. Cursor over magic skills to view their information
4. Compare the runes used in skills to what is actually needed

**Expected behavior**
If a skill has no combination runes, that section of the dialog shouldnt display to reduce confusion.

**Screenshots**
![melvordefect](https://user-images.githubusercontent.com/76179203/104796754-20f41280-5787-11eb-8abd-d267f46f7e1c.png)

**Browser**
Firefox

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
This is done on purpose.

The reason being is that the "Use Combination Runes" refers to the checkbox you have to actually use Combination Runes. What this information is displaying is the runes that will be used if that setting is active.

Because these spells have no combination alternatives, it will use the base runes.
