### ISSUE TITLE
Completionist Cape

### ISSUE THREAD

**Issue by Eusmusia** [MelvorIdle/melvoridle.github.io#73]
After Skill Capes and Max Cape, the Completionist Cape should be added.

The Comp Cape would require 100% Mastery in all skills, Maxed skills, plus whatever other requirements could be attached such as a certain number of boss kills, etc. If more skills are added, then these would be requirements as well. Same as Rs3, the Comp cape is designed for those that have fully explored the game, have finished all of the content and have completed some of the most tedious activities available. Only die-hard fans would be even willing to attempt this cape.

The Comp cape would be among the best capes in-game just by its sheer requirements needed to obtain. The cape could come with special effects that help in combat and/or skills, such as a chance to not consume ammo, saving runes (when magic is added), etc.

**Comment by mrDLSable** [comment]
this sounds like a cool idea, until you think aboit it for a moment. I did some quick mental maths and came to the conclusion that with the current mastery system it would take literally centuries to compete this. I'll do some proper maths when I'm at my PC.

still, I expect that methods to increase mastery XP gain are on their way do I still support this idea and recommend calling it the Cape of Sable. because, why not. 😉

**Comment by MelvorIdle** [comment]
If I were to implement this, I would need to add exactly what mrDLSable suggested - a way to increase mastery XP gains so it does not taking centuries to get.

**Comment by Eusmusia** [comment]
Yes. I have noticed this too, especially with larger skills, such as Smithing. 

Perhaps when some other skills are added, like possibly Herblore, adding potions that increase Mastery XP Gain would be beneficial.
