### ISSUE TITLE
Pillar of Combat Passives Not Working 

### ISSUE THREAD

**Issue by Lemonsre** [MelvorIdle/melvoridle.github.io#784]
**Description**
None of the passives under Pillar of Combat are working.

**Steps to reproduce the behaviour:**
1. Purchase Pillar of Combat
2. Evasion values under combat remain the same.
3. Use Slayer Cape (25% negation) + Hunter's Ring (10% negation) + Pillar of Combat (5% negation) and go to Dark Waters (40% Slow).
4. Attack speed is still slowed by 5%. 

**Expected behaviour**
Evasion values increase by 10%. Slayer Area Effect Negation should work.

**Browser**
Google Chrome version 89.0.4389.82.

**Are you using any scripts?**
No

**Comment by aermolae** [comment]
'+3% of max hit to min hit' also doesn't function; got a min hit of 7 with a listed max hit of 610 while pillar was active

**Comment by coolrox95** [comment]
Can confirm that the passives are broken.
Using a handy little function:
```js
 function printActiveModifiers() {
  const printList = [];
  Object.entries(playerModifiers).forEach((entry)=>{
    if (Array.isArray(entry[1])) {
      entry[1].forEach((active)=>{
        printList.push(printPlayerModifier(entry[0],[active.id,active.value]));
      })
    } else {
      if (entry[1] !== 0) {
        printList.push(printPlayerModifier(entry[0],entry[1]));
      }
    }
  })
  console.log(printList.map((listItem)=>{return listItem[0]}).join('\n'));
}
```
I found that the list of active passives when activating the combat pillar did not change.
Upon further investigation this is due to an error in `calculateAgilityModifiers`. It checks this condition to add pillar bonuses, 
```js
  if (agilityPassivePillarActive > 0 && agilityCourseCompleted) {
```
which would fail for the combat pillar as `agilityPassivePillarActive = 0` in that case.
Should be changed to: 
```js
  if (agilityPassivePillarActive > -1 && agilityCourseCompleted) {
```

**Comment by MelvorIdle** [comment]
Fixed in upcoming hotfix
