### ISSUE TITLE
Darksteel Dagger does not work in Goblin Raid

### ISSUE THREAD

**Issue by CaptainSmacakss** [MelvorIdle/melvoridle.github.io#816]
**Describe the bug**

Upon getting the Darksteel Dagger in Goblin Raid, the special attack will do no damage.  It looks like the bleed applies but it just keeps missing.

**To Reproduce**
1. Get to wave 10+ on Goblin Raid
2. Click on weapon for new item and select Darksteel Dagger if applicable
3. Continue the raid and see the health bar of the goblin after your attack and you'll notice that it says miss for all bleed hits.

**Expected behavior**
The Darksteel dagger special attack shouldn't consistently miss.  It should be bleeding these goblin bois

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.
Firefox

**Console output**
Please open the console by pressing F12 and copy it here.

**Are you using any scripts?**
Please let us know if you are using scripts the time this bug occurred.
I have the combat simulator, but I haven't loaded it in since update v0.19

**Comment by coolrox95** [comment]
Seems like this issue is due to `playerSpecialAttacks[specID].extraBleedDmg` only being applied to bleed damage for bleed specials that do a X% of Damage dealt of an attack (and only the ones where `totalBleedHPCustom` is undefined). As a result the dagger is only doing the 4% of max hp part (which is probably getting rounded down to 0 since the golbins have low health).

The bleed calculation as it is is kinda confusing so I wrote a function that Malcs is welcome to use. It should produce the intended total bleed damage for specials, and allow some additional flexibility in being able to combine the % of damage, % of maxHP and fixed amount bleed damages.
```js
function computeTotalBleedDamage(specID, damageToEnemy) {
  const specialAttack = playerSpecialAttacks[specID];
  let totalBleedHP = 0;
  if (specialAttack.totalBleedHP > 0) {
    let bleedDamageMult = specialAttack.totalBleedHP;
    // Hardcoded exception to do 2.5x damage if below maxHP
    if (specID === 28 && combatData.enemy.hitpoints < combatData.enemy.maxHitpoints) bleedDamageMult = 2.5;
    totalBleedHP = damageToEnemy * bleedDamageMult;
    if (specialAttack.totalBleedHPCustom === 1) totalBleedHP *= Math.random();
  }
  if (specialAttack.totalBleedHPPercent !== undefined) {
    totalBleedHP += combatData.enemy.maxHitpoints * specialAttack.totalBleedHPPercent / 100;
  }
  if (specialAttack.extraBleedDmg !== undefined) totalBleedHP += getNumberMultiplierValue(specialAttack.extraBleedDmg);
  return totalBleedHP;
}
```
