### ISSUE TITLE
Cave Fish not appearing in Cooking list

### ISSUE THREAD

**Issue by MuscularGoddess** [MelvorIdle/melvoridle.github.io#836]
**Describe the bug**
I have plenty of cave fish in my inventory but when I go to the cooking skill and check the drop down list to choose which fish to cook, I don't see cave fish. I used to be able to do it (I have 80+ levels in cooking it) so not sure why I'm not able to do it now.

**To Reproduce**
1. Go to Cooking ability
2. Click on Select Your Food
3. Not able to see Cave Fish

**Expected behavior**
See Cave Fish in the cooking list

**Screenshots**
![IMG-4028](https://user-images.githubusercontent.com/76112687/111157566-678aa100-856d-11eb-9cd3-f2e57e7353ba.PNG)
![IMG-4029](https://user-images.githubusercontent.com/76112687/111157568-68233780-856d-11eb-9689-783c74eb4623.PNG)

**Browser**
iOS on iPhone 11

**Console output**
N/A

**Are you using any scripts?**
None

**Comment by jttheghost** [comment]
Does not affect Steam v0.19 - might be a visual bug where cave fish is at the top of the list and getting cut off on the phone since the banner is on top of the menu. See image below for comparison to pc/steam

@MuscularGoddess try re-arranging your inventory and seeing if the cave fish works if it's later in your inventory


![image](https://user-images.githubusercontent.com/28493765/111231749-2a033380-85c0-11eb-8a04-56728fd74d52.png)

**Comment by MelvorIdle** [comment]
You need to position the box so it drops down, or simply change the position of cave fish in your bank to a different spot as the menu is based on that.

This is being addressed in the planned cooking rework
